Repository overte-org/overte, pull requests merged in 2022-09, with the labels that each got.

#183 Places app: Add a timeout to the request to the MS server.
  scripts/system/places/places.html
  scripts/system/places/places.js
Labels: CR approved, QA approved

#189 Notifications: Local Entities, emissive, HMD bugs fixes, new HMD positioning, settings ON/OFF.
  interface/src/ui/PreferencesDialog.cpp
  interface/src/ui/Snapshot.h
  scripts/system/notifications.js
Labels: needs CR, needs QA

#134 Added screenshot format selection with PNG, JPEG and WEBP support
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/PreferencesDialog.cpp
  interface/src/ui/Snapshot.cpp
  interface/src/ui/Snapshot.h
Labels: CR approved, QA approved

#193 Fix missing comma in avatarbookmarks.json
  interface/resources/avatar/bookmarks/avatarbookmarks.json
Labels: CR approved

#191 Fixed create app entity intersections in VR, increased default voxel resolution
  scripts/system/create/editModes/editVoxels.js
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
  scripts/system/create/qml/NewPolyVoxDialog.qml
Labels: CR approved, QA approved
