Repository overte-org/overte, pull requests merged in 2022-12, with the labels that each got.

#84 Initial texture benchmark test
  tests/ktx/src/KtxBenchmarkTests.cpp
  tests/ktx/src/KtxBenchmarkTests.h
Labels: CR approved

#270 Clear _meshStates after warning, not before.
  libraries/render-utils/src/Model.cpp
Labels: CR approved, needs QA

#262 Start REUSE compliance
  .clang-format
  .editorconfig
  .eslintrc.js
  .gitattributes
  .github/CODEOWNERS
  .github/stale.yml
  .github/workflows/dump.yml
  .github/workflows/master_build.yml
  .github/workflows/master_deploy_apidocs.yml
  .github/workflows/master_deploy_doxygen.yml
  .github/workflows/pr_build.yml
  .gitignore
  .grenrc.js
  BUILD.md
  BUILD_ANDROID.md
  BUILD_LINUX.md
  BUILD_LINUX_CHEATSHEET.md
  BUILD_OSX.md
  BUILD_WIN.md
  CHANGELOG.md
  CODING_STANDARD.md
  CONTRIBUTING.md
  INSTALLER.md
  LICENSES/Apache-2.0.txt
  LICENSES/MIT.txt
  README.md
  README_hifi.md
  VCPKG.md
  android/build_recipes.md
  cmake/ports/webrtc/README.md
  cmake/ports/webrtc/copy-VCPKG-file-win.cmd
  interface/resources/qml/controls/README.md
  tools/README.md
Labels: CR approved

#269 Fix "may be used uninitialized" warning for blendtime
  libraries/animation/src/Rig.h
Labels: CR approved, needs QA

#221 Implement initial Blender FBX metallic support
  libraries/model-serializers/src/FBXSerializer.cpp
  libraries/model-serializers/src/FBXSerializer_Material.cpp
Labels: CR approved, needs QA

#288 Make NEW MAX ELAPSED AVERAGE trigger less sensitive
  interface/src/Application.cpp
Labels: CR approved

#291 Quick workaround for Nvidia driver bug
  .gitignore
  libraries/entities-renderer/src/paintStroke.slv
  libraries/render-utils/src/drawWorkloadProxy.slv
Labels: needs QA

#294 Secondary camera now has the same antialiasing settings as main one
  interface/src/scripting/RenderScriptingInterface.cpp
  interface/src/scripting/RenderScriptingInterface.h
Labels: CR approved, QA approved
