Repository overte-org/overte, pull requests merged in 2022-06, with the labels that each got.

#76 Fix lots of build warnings
  CMakeLists.txt
  interface/src/AvatarBookmarks.cpp
  interface/src/Bookmarks.cpp
  interface/src/InterfaceDynamicFactory.cpp
  interface/src/avatar/AvatarDoctor.cpp
  interface/src/avatar/AvatarPackager.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/commerce/Wallet.cpp
  interface/src/scripting/AssetMappingsScriptingInterface.cpp
  interface/src/scripting/GooglePolyScriptingInterface.cpp
  interface/src/ui/HMDToolsDialog.cpp
  interface/src/ui/HMDToolsDialog.h
  interface/src/ui/overlays/TextOverlay.cpp
  libraries/animation/src/AnimInverseKinematics.cpp
  libraries/animation/src/Rig.cpp
  libraries/audio/src/Sound.cpp
  libraries/avatars-renderer/src/avatars-renderer/Head.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/controllers/src/controllers/InputRecorder.cpp
  libraries/controllers/src/controllers/UserInputMapper.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableMeshPart.cpp
  libraries/graphics/src/graphics/Geometry.cpp
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/networking/src/AtpReply.cpp
  libraries/networking/src/DataServerAccountInfo.cpp
  libraries/networking/src/HMACAuth.cpp
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/RSAKeypairGenerator.cpp
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/SockAddr.cpp
  libraries/networking/src/udt/NetworkSocket.cpp
  libraries/networking/src/webrtc/WebRTCDataChannels.cpp
  libraries/octree/src/OctreeElement.cpp
  libraries/octree/src/OctreeQuery.cpp
  libraries/qml/src/qml/OffscreenSurface.cpp
  libraries/recording/src/recording/Clip.cpp
  libraries/recording/src/recording/impl/PointerClip.cpp
  libraries/script-engine/src/ArrayBufferClass.cpp
  libraries/script-engine/src/ArrayBufferViewClass.cpp
  libraries/script-engine/src/BatchLoader.cpp
  libraries/script-engine/src/ModelScriptingInterface.cpp
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/WheelEvent.cpp
  libraries/shared/src/LogHandler.cpp
  libraries/shared/src/LogHandler.h
  libraries/shared/src/SettingHelpers.cpp
  libraries/shared/src/SharedUtil.cpp
  libraries/shared/src/WarningsSuppression.h
  libraries/workload/src/workload/Space.cpp
Labels: needs CR, needs QA

#93 Implement Qt WebEngine and Chromium versions
  interface/CMakeLists.txt
  interface/resources/images/about-chromium.svg
  interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
  interface/src/AboutUtil.cpp
  interface/src/AboutUtil.h
Labels: CR approved, testing successful

#86 Fix build warnings, second iteration
  assignment-client/src/avatars/MixerAvatar.cpp
  assignment-client/src/entities/EntityServer.cpp
  assignment-client/src/octree/OctreeServer.cpp
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServerNodeData.cpp
  domain-server/src/DomainServerSettingsManager.cpp
  ice-server/src/IceServer.cpp
  interface/src/Application.cpp
  tools/ktx-tool/src/main.cpp
  tools/nitpick/src/AWSInterface.cpp
  tools/nitpick/src/TestCreator.cpp
  tools/nitpick/src/TestRunnerDesktop.cpp
  tools/oven/src/BakerCLI.cpp
  tools/vhacd-util/src/VHACDUtil.cpp
Labels: CR approved, testing successful

#106 Disable Android CI builds
  .github/workflows/pr_build.yml
Labels: CR approved

#95 Add log breakpoint system
  libraries/shared/src/Breakpoint.h
  libraries/shared/src/LogHandler.cpp
  libraries/shared/src/LogHandler.h
Labels: needs QA, QA approved

#97 Show the filename when a texture fails to load
  libraries/image/src/image/TextureProcessing.cpp
Labels: CR approved, QA approved

#100 Make the "Wrote KTX" message a debug one
  libraries/material-networking/src/material-networking/KTXCache.cpp
Labels: CR approved, QA approved

#108 Fixed allowed QML sources to point at our community apps server
  interface/src/Application.cpp
Labels: CR approved

#104 Implement Journald logging
  assignment-client/src/AssignmentClientApp.cpp
  cmake/modules/FindJournald.cmake
  domain-server/src/DomainServer.cpp
  interface/src/main.cpp
  libraries/shared/CMakeLists.txt
  libraries/shared/src/LogHandler.cpp
  libraries/shared/src/LogHandler.h
Labels: CR approved, needs QA
