Repository overte-org/overte, pull requests merged in 2022-08, with the labels that each got.

#146 Update Qt on Windows to 5.15.5 and QtWebengine to 5.15.11
  hifi_qt.py
Labels: CR approved, needs QA

#155 Replace Graphik with Fira Sans
  interface/resources/fonts/FiraSans-Medium.ttf
  interface/resources/fonts/Graphik-Medium.ttf
  interface/resources/fonts/Graphik-Regular.ttf
  interface/resources/fonts/Graphik-Semibold.ttf
  interface/resources/qml/hifi/simplifiedUI/avatarApp/AvatarApp.qml
  interface/resources/qml/hifi/simplifiedUI/avatarApp/components/AvatarAppListDelegate.qml
  interface/resources/qml/hifi/simplifiedUI/avatarApp/components/DisplayNameHeader.qml
  interface/resources/qml/hifi/simplifiedUI/helpApp/HelpApp.qml
  interface/resources/qml/hifi/simplifiedUI/helpApp/about/HelpAbout.qml
  interface/resources/qml/hifi/simplifiedUI/helpApp/controls/ControlsTable.qml
  interface/resources/qml/hifi/simplifiedUI/helpApp/controls/HelpControls.qml
  interface/resources/qml/hifi/simplifiedUI/helpApp/faq/HelpFAQ.qml
  interface/resources/qml/hifi/simplifiedUI/helpApp/support/HelpSupport.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/SettingsApp.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/dev/Dev.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/general/General.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/vr/VR.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/Button.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/CheckBox.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/RadioButton.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/Slider.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/Switch.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/TextField.qml
  interface/resources/qml/stylesUit/FiraSansMedium.qml
  interface/resources/qml/stylesUit/FiraSansRegular.qml
  interface/resources/qml/stylesUit/FiraSansSemiBold.qml
  interface/resources/qml/stylesUit/GraphikMedium.qml
  interface/resources/qml/stylesUit/GraphikSemiBold.qml
  interface/src/Application.cpp
  launchers/qt/resources/fonts/Graphik-Medium.ttf
  launchers/qt/resources/fonts/Graphik-Regular.ttf
  launchers/qt/resources/fonts/Graphik-Semibold.ttf
  launchers/win32/Launcher.rc
  launchers/win32/LauncherDlg.cpp
  launchers/win32/res/FiraSansbold.ttf
  launchers/win32/res/FiraSansregular.ttf
  launchers/win32/res/Graphikbold.ttf
  launchers/win32/res/Graphikregular.ttf
  screenshare/src/resources/FiraSans-Regular.ttf
  screenshare/src/resources/Graphik-Regular.ttf
  screenshare/src/styles.css
  scripts/simplifiedUI/simplifiedEmote/emojiApp/ui/qml/SimplifiedEmoji.qml
  scripts/simplifiedUI/simplifiedEmote/ui/qml/SimplifiedEmoteIndicator.qml
  tools/jsdoc/hifi-jsdoc-template/static/fonts/FiraSans-Regular.ttf
  tools/jsdoc/hifi-jsdoc-template/static/fonts/FiraSans-SemiBold.ttf
  tools/jsdoc/hifi-jsdoc-template/static/fonts/Graphik-Regular.otf
  tools/jsdoc/hifi-jsdoc-template/static/fonts/Graphik-Semibold.otf
  tools/jsdoc/hifi-jsdoc-template/static/styles/jsdoc.css
Labels: CR approved, QA approved

#157 Fix apidocs example files
  interface/src/avatar/MyAvatar.h
  libraries/avatars/src/AvatarData.h
  tools/jsdoc/hifi-jsdoc-template/static/examples/ClapHands_Standing.fbx
  tools/jsdoc/hifi-jsdoc-template/static/examples/armpose.png
  tools/jsdoc/hifi-jsdoc-template/static/examples/cowboy-hat.fbx
  tools/jsdoc/hifi-jsdoc-template/static/examples/stretched-neck.png
  tools/jsdoc/hifi-jsdoc-template/static/examples/t-pose.png
Labels: CR approved

#164 Update GitHub Actions to Ubuntu 20.04
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
Labels: needs CR

#169 Fix --disable-displays and --disable-inputs arguments
  interface/src/Application.cpp
  interface/src/main.cpp
Labels: CR approved, needs QA

#162 Update VCPKG
  .github/workflows/pr_build.yml
  CMakeLists.txt
  cmake/externals/GifCreator/CMakeLists.txt
  cmake/externals/LibOVR/CMakeLists.txt
  cmake/externals/LibOVRPlatform/CMakeLists.txt
  cmake/externals/crashpad/CMakeLists.txt
  cmake/externals/neuron/CMakeLists.txt
  cmake/externals/serverless-content/CMakeLists.txt
  cmake/externals/sixense/CMakeLists.txt
  cmake/externals/steamworks/CMakeLists.txt
  cmake/externals/tbb/CMakeLists.txt
  cmake/externals/wasapi/CMakeLists.txt
  cmake/ports/aristo/portfile.cmake
  cmake/ports/bullet3/portfile.cmake
  cmake/ports/draco/portfile.cmake
  cmake/ports/etc2comp/portfile.cmake
  cmake/ports/glad/portfile.cmake
  cmake/ports/gli/portfile.cmake
  cmake/ports/glm/portfile.cmake
  cmake/ports/glslang/portfile.cmake
  cmake/ports/hifi-scribe/portfile.cmake
  cmake/ports/liblo/portfile.cmake
  cmake/ports/nlohmann-json/portfile.cmake
  cmake/ports/nvtt/portfile.cmake
  cmake/ports/openexr/portfile.cmake
  cmake/ports/openssl-android/portfile.cmake
  cmake/ports/openssl-unix/portfile.cmake
  cmake/ports/openssl-windows/portfile.cmake
  cmake/ports/openvr/portfile.cmake
  cmake/ports/opus/portfile.cmake
  cmake/ports/polyvox/portfile.cmake
  cmake/ports/quazip/portfile.cmake
  cmake/ports/sdl2/portfile.cmake
  cmake/ports/shaderc/portfile.cmake
  cmake/ports/spirv-cross/portfile.cmake
  cmake/ports/spirv-tools/portfile.cmake
  cmake/ports/sranipal/portfile.cmake
  cmake/ports/tbb/portfile.cmake
  cmake/ports/vhacd/portfile.cmake
  cmake/ports/vulkanmemoryallocator/portfile.cmake
  cmake/ports/webrtc/portfile.cmake
  cmake/ports/zlib/portfile.cmake
  hifi_vcpkg.py
  prebuild.py
Labels: CR approved, QA approved

#165 Update NVTT
  cmake/ports/nvtt/CONTROL
  cmake/ports/nvtt/portfile.cmake
Labels: CR approved, QA approved

#158 Fix paths for importing images and opening directories
  interface/src/Application.cpp
Labels: needs CR, needs QA

#172 Fix OBJ-Serializer using wrong decimal separator
  libraries/model-serializers/src/OBJSerializer.cpp
Labels: CR approved, needs QA
