Repository overte-org/overte, pull requests merged in 2022-11, with the labels that each got.

#244 Create app: PolyVox properties tootips
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: CR approved, QA approved

#236 Optimize settings system
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/scripting/SettingsScriptingInterface.cpp
  interface/src/scripting/SettingsScriptingInterface.h
  libraries/shared/src/SettingHandle.cpp
  libraries/shared/src/SettingHandle.h
  libraries/shared/src/SettingHelpers.cpp
  libraries/shared/src/SettingInterface.cpp
  libraries/shared/src/SettingInterface.h
  libraries/shared/src/SettingManager.cpp
  libraries/shared/src/SettingManager.h
  tests/shared/CMakeLists.txt
  tests/shared/src/SettingsTests.cpp
  tests/shared/src/SettingsTests.h
Labels: CR approved

#240 CVE-2007-4559 Patch
  hifi_utils.py
Labels: needs QA

#247 Disable Metadata "exporter" by default
  domain-server/resources/describe-settings.json
Labels: needs CR

#177 Create audio tests for AudioClient and codecs
  tests/audio/CMakeLists.txt
  tests/audio/src/AudioTests.cpp
  tests/audio/src/AudioTests.h
  tests/audio/src/CodecTests.cpp
  tests/audio/src/CodecTests.h
Labels: CR approved, needs QA

#263 Fix crash with models from ReadyPlayerMe by adding extra validation.
  libraries/hfm/src/hfm/HFM.h
  libraries/model-serializers/src/GLTFSerializer.cpp
  tests/model-serializers/CMakeLists.txt
  tests/model-serializers/src/ModelSerializersTests.cpp
  tests/model-serializers/src/ModelSerializersTests.h
Labels: needs CR, QA approved

#267 Update SPIR-V to 2022.4. Fixes build on Fedora 37.
  cmake/ports/spirv-tools/portfile.cmake
Labels: CR approved, QA approved
