Repository overte-org/overte, pull requests merged in 2022-07, with the labels that each got.

#99 Fix replace avatar url option
  interface/src/main.cpp
Labels: CR approved, needs QA

#102 Change cmake policy CMP0074 to NEW
  cmake/init.cmake
Labels: CR approved, needs QA

#103 Change --ignore-gpu-blacklist to --ignore-gpu-blocklist
  interface/src/main.cpp
Labels: CR approved, needs QA

#112 Changed screenshot format to PNG
  interface/src/Application.cpp
  interface/src/ui/Snapshot.cpp
Labels: CR approved, QA approved

#111 Add full body tracking for Windows MR headsets on SteamVR
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
  interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml
Labels: CR approved

#121 Download dependencies from overte.org
  CMakeLists.txt
  tools/qt-builder/README.md
Labels: CR approved

#120 Fix bug in naming animated screenshots since the change to PNG
  interface/src/ui/SnapshotAnimated.cpp
Labels: CR approved

#118 Places App: "Add MS node" capability
  scripts/system/places/federation.json
  scripts/system/places/places.css
  scripts/system/places/places.html
  scripts/system/places/places.js
Labels: CR approved, QA approved

#125 Update Ubuntu 18.04 Qt package
  hifi_qt.py
  tools/qt-builder/Dockerfile_Ubuntu_18.04_Qt5
  tools/qt-builder/README.md
Labels: needs CR, needs QA

#123 Update zlib to 1.2.12, improve hosting
  cmake/ports/zlib/portfile.cmake
Labels: CR approved, needs QA

#143 Change standard automatic networking setting
  domain-server/resources/describe-settings.json
Labels: needs QA

#140 Fix voxel deadlock and improve performance
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
Labels: needs QA

#144 Analog control scheme enabled in VR by default
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: needs CR, needs QA
