Repository overte-org/overte, pull requests merged in 2023-10, with the labels that each got.

#669 Fix MicBar to not spam thousands of TypeError messages on Windows
  interface/resources/qml/hifi/audio/MicBarApplication.qml
Labels: CR approved

#663 Added distance-based LOD
  interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
  interface/src/Application.cpp
  interface/src/LODManager.cpp
  interface/src/LODManager.h
  interface/src/PerformanceManager.cpp
  interface/src/scripting/PerformanceScriptingInterface.h
  libraries/render/src/render/Args.h
  libraries/render/src/render/CullTask.cpp
Labels: enhancement, needs CR, needs QA

#671 Fix local entity grab in VR
  scripts/system/controllers/controllerModules/nearParentGrabOverlay.js
Labels: bug, needs CR, QA approved

#645 Added support for QML inside web-entities.
  interface/resources/qml/+android_interface/Web3DSurface.qml
  interface/resources/qml/+android_interface/Web3DSurfaceAndroid.qml
  interface/resources/qml/Web3DSurface.qml
  interface/resources/qml/controlsUit/ProxyWebView.qml
  interface/resources/serverless/Scripts/Wizard.qml
  interface/resources/serverless/Scripts/wizardLoader.js
  interface/src/Application.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  scripts/system/+android_interface/androidControls.js
  scripts/system/+android_interface/clickWeb.js
  scripts/system/+android_interface/modes.js
  scripts/system/+android_interface/radar.js
Labels: CR approved, needs QA

#690 Fix entity server memory leak and improve performance
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
Labels: bug, needs CR, needs QA
