Repository overte-org/overte, pull requests merged in 2023-09, with the labels that each got.

#611 Initial support for HDR lightmaps
  libraries/image/src/image/TextureProcessing.cpp
  libraries/image/src/image/TextureProcessing.h
Labels: enhancement, needs CR, needs QA

#634 Fix loading avatars from Dropbox due to URLs containing parameters
  libraries/model-serializers/src/FSTReader.cpp
Labels: CR approved, needs QA

#636 Rewrite Dropbox URLs to force downloads, even if the user uses a preview URL
  libraries/networking/src/ResourceCache.cpp
Labels: CR approved, needs QA

#579 Avatar Smoothing
  script-archive/accelerationFilterApp.js
  script-archive/exponentialFilterApp.js
  scripts/developer/characterSmoothing/characterSmoothing.js
  scripts/developer/characterSmoothing/img/icon-a.png
  scripts/developer/characterSmoothing/img/icon.png
  scripts/developer/characterSmoothing/ui/index.css
  scripts/developer/characterSmoothing/ui/index.html
  scripts/developer/characterSmoothing/ui/index.js
  scripts/developer/characterSmoothing/ui/index.scss
  scripts/developer/characterSmoothing/ui/theme.css
Labels: CR approved
