Repository overte-org/overte, pull requests merged in 2023-06, with the labels that each got.

#436 fixed mic not changing color when not in use
  interface/resources/qml/hifi/audio/MicBarApplication.qml
Labels: CR approved

#437 Fix GitHub Actions not cleaning up after itself
  .github/workflows/linux_server_build.yml
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
Labels: CR approved, server

#444 Hide private methods and QObject signals from script engine
  libraries/script-engine/src/v8/ScriptObjectV8Proxy.cpp
  scripts/defaultScripts.js
  scripts/system/controllers/controllerScripts.js
Labels: needs CR, QA approved

#445 Fix resetting the settings
  interface/src/CrashRecoveryHandler.cpp
  libraries/shared/src/SettingHandle.cpp
  libraries/shared/src/SettingHandle.h
  libraries/shared/src/SettingManager.cpp
  libraries/shared/src/SettingManager.h
Labels: needs QA

#450 Fix wrong syntax for JSDoc comments
  libraries/script-engine/src/ScriptManagerScriptingInterface.h
  libraries/script-engine/src/ScriptValueUtils.cpp
  libraries/script-engine/src/ScriptValueUtils.h
Labels: CR approved

#446 Build with crash reporting against Sentry
  .github/workflows/linux_server_build.yml
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
Labels: server

#452 Build libnode from source
  .gitignore
  cmake/ports/node/portfile.cmake
Labels: CR approved, QA approved

#473 ForceHtmlAudioOutputDeviceUpdate fix
  .gitignore
  interface/resources/html/createGlobalEventBridge.js
Labels: CR approved, needs QA

#465 Added FOV setting to graphics menu
  interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
  interface/src/scripting/RenderScriptingInterface.cpp
  interface/src/scripting/RenderScriptingInterface.h
Labels: CR approved, QA approved

#477 Fix not working entity list in Create App
  scripts/system/create/entityList/html/js/entityList.js
  tools/nitpick/AppDataHighFidelity/Interface/avatarbookmarks.json
Labels: needs CR

#480 Improve crash handler
  interface/src/CrashHandler.h
  interface/src/CrashHandler_Breakpad.cpp
  interface/src/CrashHandler_Crashpad.cpp
  interface/src/CrashHandler_None.cpp
  interface/src/CrashRecoveryHandler.cpp
  interface/src/CrashRecoveryHandler.h
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/main.cpp
  interface/src/ui/PreferencesDialog.cpp
  libraries/networking/src/UserActivityLogger.cpp
  libraries/networking/src/UserActivityLogger.h
Labels: needs CR, needs QA

#478 VR overlay recenter now triggers on hasDriveInput rising edge
  interface/src/ui/OverlayConductor.cpp
  interface/src/ui/OverlayConductor.h
Labels: CR approved, QA approved, fix before release

#487 Fix bug with clicking on triggerable objects in VR
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: CR approved, fix before release

#481 Fix thumbstick press issue
  interface/resources/controllers/index.json
  libraries/plugins/src/plugins/InputConfiguration.h
  plugins/openvr/src/ViveControllerManager.cpp
Labels: CR approved, QA approved, fix before release

#490 Laser pointers on overlays fix
  scripts/system/libraries/pointersUtils.js
Labels: CR approved, QA approved, fix before release

#498 Fixed Create App performance when moving objects
  scripts/system/create/edit.js
  scripts/system/create/entityList/entityList.js
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
  scripts/system/libraries/entityIconOverlayManager.js
Labels: CR approved, QA approved, fix before release

#495 Fixed laser pointer blinking issue
  interface/src/raypick/LaserPointer.cpp
  interface/src/raypick/ParabolaPointer.cpp
  scripts/system/controllers/controllerScripts.js
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
Labels: CR approved, QA approved
