Repository overte-org/overte, pull requests merged in 2023-11, with the labels that each got.

#691 Remove File API and limit audio recording file location
  interface/resources/qml/hifi/+webengine/DesktopWebEngine.qml
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/ArchiveDownloadInterface.cpp
  interface/src/ArchiveDownloadInterface.h
  interface/src/scripting/Audio.cpp
  interface/src/scripting/Audio.h
  libraries/script-engine/src/FileScriptingInterface.h
  libraries/script-engine/src/ScriptManager.cpp
Labels: bug, CR approved, QA approved

#686 Discord rich presence support
  cmake/macros/TargetDiscordRPC.cmake
  cmake/ports/discord-rpc/disable-downloading.patch
  cmake/ports/discord-rpc/portfile.cmake
  cmake/ports/discord-rpc/vcpkg.json
  cmake/ports/hifi-client-deps/CONTROL
  cmake/ports/rapidjson/portfile.cmake
  cmake/ports/rapidjson/vcpkg.json
  interface/CMakeLists.txt
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/DiscordRichPresence.cpp
  interface/src/DiscordRichPresence.h
  libraries/networking/src/AddressManager.cpp
Labels: needs CR, needs QA

#696 Fix Windows GitHub Actions workflows
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
Labels: needs CR

#672 Prevent the chat bar from popping up when VR headset is on
  scripts/communityScripts/chat/FloofChat.js
Labels: bug, CR approved, QA approved

#700 Disable Oculus plugin by default and add a setting to enable it
  interface/resources/qml/hifi/dialogs/GeneralPreferencesDialog.qml
  interface/resources/qml/hifi/tablet/TabletGeneralPreferences.qml
  interface/src/ui/PreferencesDialog.cpp
  libraries/plugins/src/plugins/PluginManager.cpp
  libraries/plugins/src/plugins/PluginManager.h
  plugins/openvr/src/OpenVrHelpers.cpp
Labels: bug, CR approved, QA approved

#706 Fix for custom graphics setting
  interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
  interface/src/PerformanceManager.cpp
  interface/src/PerformanceManager.h
  interface/src/scripting/PerformanceScriptingInterface.h
  libraries/platform/src/platform/Profiler.h
Labels: bug, CR approved, QA approved

#697 Fixed incorrect Script.require behavior
  libraries/script-engine/src/v8/ScriptEngineV8.cpp
Labels: CR approved, QA approved

#708 Call somethingChangedNotification() from setLocalJointXXXX
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
Labels: CR approved

#701 Switch to self-hosted Linux amd64 GitHub Actions Runner
  .github/workflows/linux_server_build.yml
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
  tools/ci-scripts/linux-ci/Dockerfile_build_ubuntu-20.04
Labels: CR approved

#714 Disabled Oculus plugin in additional place
  plugins/oculus/src/OculusHelpers.cpp
Labels: bug, CR approved, QA approved

#722 [ICE] Added command line arguments
  ice-server/src/IceServer.cpp
  tools/ice-client/src/ICEClientApp.cpp
Labels: enhancement, needs CR, QA approved

#723 Discord Rich Presence v2
  interface/src/DiscordRichPresence.cpp
  interface/src/DiscordRichPresence.h
  interface/src/main.cpp
Labels: CR approved, needs QA

#729 Changed gravity constant to a more realistic one
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/physics/src/CharacterController.cpp
  libraries/shared/src/AvatarConstants.h
Labels: CR approved, QA approved

#736 Improve game rate by moving squeezeHands.js to a separate thread
  scripts/defaultScripts.js
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerScripts.js
Labels: CR approved, QA approved

#724 Fix luci
  scripts/developer/utilities/lib/skit/Page.js
  scripts/developer/utilities/render/luci.js
  scripts/developer/utilities/render/luci/Bloom.qml
  scripts/developer/utilities/render/luci/BoundingBoxes.qml
  scripts/developer/utilities/render/luci/Culling.qml
  scripts/developer/utilities/render/luci/Framebuffer.qml
  scripts/developer/utilities/render/luci/ShadingModel.qml
Labels: bug, CR approved, QA approved
