Repository overte-org/overte, pull requests merged in 2023-08, with the labels that each got.

#540 Fixed deadlock when entity script engines are being reset.
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
Labels: needs CR, needs QA

#535 Build node from source on aarch64
  cmake/ports/node/portfile.cmake
Labels: needs CR, server

#564 Add JS profiling API
  libraries/script-engine/src/ScriptEngine.h
  libraries/script-engine/src/ScriptManager.cpp
  libraries/script-engine/src/ScriptManagerScriptingInterface.cpp
  libraries/script-engine/src/ScriptManagerScriptingInterface.h
  libraries/script-engine/src/v8/ScriptEngineV8.cpp
  libraries/script-engine/src/v8/ScriptEngineV8.h
Labels: needs CR, CR approved

#573 Fixed leave messages in floofchat
  scripts/communityScripts/chat/FloofChat.js
Labels: bug, CR approved, QA approved

#566 Align functions to avoid V8 asserts in debug builds
  CMakeLists.txt
Labels: needs CR

#520 Added null pointer check for asQuickItem()
  libraries/ui/src/QmlWindowClass.cpp
Labels: CR approved

#585 Put require() in the global scope
  libraries/script-engine/src/ScriptManager.cpp
Labels: CR approved

#598 jsDoc updates/fixes
  interface/src/ui/overlays/Overlays.h
  libraries/audio/src/AudioScriptingInterface.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.h
  libraries/networking/src/ResourceCache.h
  libraries/script-engine/src/PointerEvent.h
  libraries/script-engine/src/ScriptManagerScriptingInterface.h
  tools/jsdoc/hifi-jsdoc-template/static/examples/Silly Dancing.fbx
  tools/jsdoc/hifi-jsdoc-template/static/examples/beach-tide-amplified.wav
Labels: CR approved

#574 Fix most of the crash causes on script engine reload/shutdown
  interface/src/Application.cpp
  libraries/controllers/src/controllers/Actions.cpp
  libraries/controllers/src/controllers/InputDevice.cpp
  libraries/controllers/src/controllers/StateController.cpp
  libraries/controllers/src/controllers/UserInputMapper.cpp
  libraries/controllers/src/controllers/UserInputMapper.h
  libraries/controllers/src/controllers/impl/Endpoint.h
  libraries/controllers/src/controllers/impl/endpoints/ActionEndpoint.h
  libraries/controllers/src/controllers/impl/endpoints/AnyEndpoint.h
  libraries/controllers/src/controllers/impl/endpoints/ArrayEndpoint.h
  libraries/controllers/src/controllers/impl/endpoints/CompositeEndpoint.h
  libraries/controllers/src/controllers/impl/endpoints/InputEndpoint.h
  libraries/controllers/src/controllers/impl/endpoints/JSEndpoint.h
  libraries/controllers/src/controllers/impl/endpoints/ScriptEndpoint.cpp
  libraries/controllers/src/controllers/impl/endpoints/ScriptEndpoint.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/script-engine/src/ScriptEngine.h
  libraries/script-engine/src/ScriptEngines.cpp
  libraries/script-engine/src/ScriptEngines.h
  libraries/script-engine/src/ScriptManager.cpp
  libraries/script-engine/src/ScriptManager.h
  libraries/script-engine/src/v8/ScriptEngineV8.cpp
  libraries/script-engine/src/v8/ScriptEngineV8.h
  libraries/script-engine/src/v8/ScriptObjectV8Proxy.cpp
  libraries/script-engine/src/v8/ScriptObjectV8Proxy.h
  libraries/script-engine/src/v8/ScriptValueV8Wrapper.cpp
Labels: bug, needs CR, needs QA

#604 Fix issues with flow bones
  libraries/animation/src/Flow.cpp
  libraries/animation/src/Flow.h
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
Labels: bug, CR approved, QA approved
