Repository overte-org/overte, pull requests merged in 2023-12, with the labels that each got.

#746 Fix setting external port and IP address for manual networking modes
  domain-server/resources/web/settings/js/settings.js
  domain-server/src/DomainServer.cpp
Labels: bug, CR approved, QA approved

#710 Add initial benchmarks for the script engine
  tests/script-engine/src/ScriptEngineBenchmarkTests.cpp
  tests/script-engine/src/ScriptEngineBenchmarkTests.h
Labels: needs CR

#747 particle billboarding is wrong in VR
  libraries/entities-renderer/src/textured_particle.slv
Labels: enhancement, CR approved, QA approved

#753 Disable Neuron by default
  CMakeLists.txt
  plugins/CMakeLists.txt
Labels: CR approved, needs QA

#716 Reorganize startup to allow more control over plugins
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/main.cpp
  libraries/plugins/src/plugins/PluginManager.cpp
  libraries/plugins/src/plugins/PluginManager.h
Labels: CR approved, needs QA

#744 Script performance improvements
  interface/src/scripting/ControllerScriptingInterface.h
  libraries/script-engine/src/v8/FastScriptValueUtils.cpp
  libraries/script-engine/src/v8/ScriptEngineV8.cpp
  libraries/script-engine/src/v8/ScriptEngineV8_cast.cpp
  libraries/script-engine/src/v8/ScriptObjectV8Proxy.cpp
  libraries/script-engine/src/v8/ScriptValueV8Wrapper.cpp
  scripts/simplifiedUI/ui/simplifiedNametag/resources/modules/pickRayController.js
  scripts/system/away.js
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/equipEntity.js
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/controllers/controllerModules/farGrabEntity.js
  scripts/system/controllers/controllerModules/hudOverlayPointer.js
  scripts/system/controllers/controllerModules/inEditMode.js
  scripts/system/controllers/controllerModules/teleport.js
  scripts/system/controllers/controllerModules/trackedHandTablet.js
  scripts/system/controllers/controllerModules/trackedHandWalk.js
  scripts/system/controllers/handTouch.js
  scripts/system/controllers/squeezeHands.js
  scripts/system/controllers/toggleAdvancedMovementForHandControllers.js
  scripts/system/controllers/touchControllerConfiguration.js
  scripts/system/controllers/viveControllerConfiguration.js
  scripts/system/create/editModes/editVoxels.js
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
  scripts/system/emote.js
  scripts/system/fingerPaint.js
  scripts/system/libraries/Trigger.js
  scripts/system/libraries/WebTablet.js
  scripts/system/libraries/controllerDispatcherUtils.js
  scripts/system/libraries/controllers.js
  scripts/system/makeUserConnection.js
  scripts/system/miniTablet.js
  scripts/system/mod.js
  scripts/system/notifications.js
  scripts/system/pal.js
  scripts/system/tablet-ui/tabletUI.js
Labels: CR approved, QA approved

#769 Removing markdown from floof chat
  scripts/communityScripts/chat/FloofChat.html
  scripts/communityScripts/chat/FloofChat.js
Labels: enhancement, CR approved, QA approved

#768 Fix a bug in Entities.getEntityProperties
  interface/src/Application.cpp
  interface/src/raypick/LaserPointer.cpp
  interface/src/raypick/ParabolaPick.cpp
  interface/src/raypick/PathPointer.cpp
  interface/src/raypick/RayPick.cpp
  interface/src/ui/Keyboard.cpp
  libraries/entities/src/AmbientLightPropertyGroup.cpp
  libraries/entities/src/AmbientLightPropertyGroup.h
  libraries/entities/src/AnimationPropertyGroup.cpp
  libraries/entities/src/AnimationPropertyGroup.h
  libraries/entities/src/BloomPropertyGroup.cpp
  libraries/entities/src/BloomPropertyGroup.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemPropertiesMacros.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/entities/src/GrabPropertyGroup.cpp
  libraries/entities/src/GrabPropertyGroup.h
  libraries/entities/src/HazePropertyGroup.cpp
  libraries/entities/src/HazePropertyGroup.h
  libraries/entities/src/KeyLightPropertyGroup.cpp
  libraries/entities/src/KeyLightPropertyGroup.h
  libraries/entities/src/PropertyGroup.h
  libraries/entities/src/PulsePropertyGroup.cpp
  libraries/entities/src/PulsePropertyGroup.h
  libraries/entities/src/RingGizmoPropertyGroup.cpp
  libraries/entities/src/RingGizmoPropertyGroup.h
  libraries/entities/src/SkyboxPropertyGroup.cpp
  libraries/entities/src/SkyboxPropertyGroup.h
  scripts/system/controllers/controllerModules/nearParentGrabOverlay.js
  scripts/system/controllers/controllerModules/webSurfaceLaserInput.js
Labels: CR approved, QA approved

#770 Fixed returnNothingOnEmptyPropertyFlags
  libraries/entities/src/EntityItemProperties.cpp
Labels: CR approved, QA approved

#576 :sparkles: "Update Existing Avatar" now properly updates the fst file
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter/AvatarExporter.cs
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter/FST.cs
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter/FST.cs.meta
  tools/unity-avatar-exporter/Assets/README.txt
  tools/unity-avatar-exporter/avatarExporter.unitypackage
Labels: enhancement, work in progress
