Repository overte-org/overte, pull requests merged in 2023-05, with the labels that each got.

#403 Places App: Enter to teleport
  scripts/system/places/places.html
Labels: CR approved

#397 Places app: support for file URI scheme
  scripts/system/places/places.html
Labels: CR approved

#412 Update tbb
  cmake/ports/tbb/CMakeLists.txt
  cmake/ports/tbb/CONTROL
  cmake/ports/tbb/add-find-dependency.patch
  cmake/ports/tbb/fix-static-build.patch
  cmake/ports/tbb/portfile.cmake
  libraries/shared/src/TBBHelpers.h
Labels: CR approved, QA approved

#374 Fix NVTT compilation on Visual Studio 2022
  cmake/ports/nvtt/CONTROL
  cmake/ports/nvtt/portfile.cmake
Labels: CR approved

#430 Disable libOVR on MSVC 2022 for now
  plugins/oculus/CMakeLists.txt
Labels: CR approved

#410 Clear directory of aarch64 runner
  .github/workflows/linux_server_build.yml
  .github/workflows/pr_build.yml
Labels: server
