Repository overte-org/overte, pull requests merged in 2023-07, with the labels that each got.

#507 Fix Create App search and URLs in entity list
  scripts/system/create/entityList/html/js/entityList.js
Labels: CR approved, QA approved

#510 Restore the original dimensions of the bubble (for the "Shield" app.)
  scripts/system/bubble.js
Labels: CR approved, QA approved

#513 Truncate logs read by FileLogger
  interface/src/ui/LogDialog.cpp
  libraries/shared/src/shared/AbstractLoggerInterface.h
  libraries/shared/src/shared/FileLogger.cpp
  libraries/shared/src/shared/FileLogger.h
Labels: CR approved

#482 Crash handler on server
  assignment-client/CMakeLists.txt
  assignment-client/src/AssignmentClientApp.cpp
  assignment-client/src/assets/AssetServer.cpp
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/entities/EntityServer.cpp
  assignment-client/src/main.cpp
  assignment-client/src/messages/MessagesMixer.cpp
  assignment-client/src/octree/OctreeServer.cpp
  assignment-client/src/scripts/EntityScriptServer.cpp
  domain-server/CMakeLists.txt
  domain-server/resources/describe-settings.json
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  domain-server/src/DomainServerSettingsManager.cpp
  domain-server/src/DomainServerSettingsManager.h
  domain-server/src/main.cpp
  interface/src/Application.cpp
  interface/src/CrashRecoveryHandler.cpp
  interface/src/DiscoverabilityManager.cpp
  interface/src/Menu.cpp
  interface/src/graphics/RenderEventHandler.cpp
  interface/src/main.cpp
  libraries/networking/CMakeLists.txt
  libraries/networking/src/Assignment.cpp
  libraries/networking/src/Assignment.h
  libraries/networking/src/UserActivityLogger.cpp
  libraries/networking/src/UserActivityLogger.h
  libraries/networking/src/crash-handler/CrashHandler.cpp
  libraries/networking/src/crash-handler/CrashHandler.h
  libraries/networking/src/crash-handler/CrashHandlerBackend.h
  libraries/networking/src/crash-handler/CrashHandlerBackend_Breakpad.cpp
  libraries/networking/src/crash-handler/CrashHandlerBackend_Crashpad.cpp
  libraries/networking/src/crash-handler/CrashHandlerBackend_None.cpp
  tools/oven/CMakeLists.txt
  tools/oven/src/OvenCLIApplication.cpp
  tools/oven/src/OvenCLIApplication.h
  tools/oven/src/main.cpp
Labels: CR approved, QA approved

#518 Store annotations before the crash handler initializes
  libraries/networking/src/crash-handler/CrashHandler.cpp
  libraries/networking/src/crash-handler/CrashHandler.h
Labels: needs CR, needs QA

#519 Fix script error logging
  libraries/script-engine/src/v8/ScriptEngineV8.cpp
  libraries/script-engine/src/v8/ScriptEngineV8.h
  libraries/script-engine/src/v8/ScriptObjectV8Proxy.cpp
  libraries/script-engine/src/v8/ScriptProgramV8Wrapper.cpp
  libraries/script-engine/src/v8/ScriptValueV8Wrapper.cpp
Labels: needs CR, needs QA

#522 Fix the link on the place name to use the right hifiurl
  scripts/system/places/places.html
Labels: CR approved, QA approved

#521 Fixed interface scripts failing to shutdown
  interface/src/Application.cpp
  libraries/script-engine/src/ScriptManagerScriptingInterface.cpp
  libraries/script-engine/src/ScriptManagerScriptingInterface.h
Labels: CR approved, needs QA

#525 Remove redundant policy from CMakeLists.txt
  CMakeLists.txt
Labels: CR approved
