Repository overte-org/overte, pull requests merged in 2024-03, with the labels that each got.

#841 Fixed avatar volume adjustment
  assignment-client/src/audio/AudioMixerClientData.cpp
Labels: bug, CR approved, QA approved

#820 Respect cull face during shadow pass
  libraries/gpu/src/gpu/State.h
  libraries/render-utils/src/HighlightEffect.cpp
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render/src/render/ShapePipeline.h
Labels: bug, CR approved, QA approved, NLnet

#823 Fix Developer > UI > Show Overlays + Snap UI not hiding
  interface/src/Menu.cpp
  interface/src/graphics/GraphicsEngine.cpp
  interface/src/ui/ApplicationOverlay.h
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/Overlays.h
Labels: bug, CR approved, QA approved

#814 Web Entity wantsKeyboardFocus
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/WebEntityItem.cpp
  libraries/entities/src/WebEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: documentation, enhancement, CR approved, QA approved, server, NLnet

#840 Fixed blendshapes in gltf importer
  libraries/model-serializers/src/GLTFSerializer.cpp
Labels: CR approved, needs QA

#855 Fix require behavior for modules
  libraries/script-engine/src/v8/ScriptEngineV8.cpp
  tests/script-engine/src/ScriptEngineNetworkedTests.cpp
  tests/script-engine/src/ScriptEngineNetworkedTests.h
  tests/script-engine/src/tests/b_require.js
  tests/script-engine/src/tests/c_require.js
Labels: needs CR, QA approved

#860 Added WebP support for binary glTF
  libraries/model-serializers/src/GLTFSerializer.cpp
Labels: enhancement, CR approved, QA approved

#844 Support opaque (and black) particles
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.h
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.h
  libraries/entities-renderer/src/entities-renderer/textured_particle.slp
  libraries/entities-renderer/src/textured_particle.slf
  libraries/render-utils/src/RenderCommonTask.cpp
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render/src/render/ShapePipeline.cpp
  libraries/render/src/render/ShapePipeline.h
Labels: enhancement, needs CR, QA approved, NLnet

#866 :bug: Fixed avatar bounding box being inverted
  libraries/physics/src/CharacterController.cpp
Labels: CR approved, QA approved

#864 :wrench: Disable building electron screenshare app on windows
  CMakeLists.txt
Labels: CR approved, QA approved

#867 Fix collisions on glTF avatars
  libraries/model-serializers/src/GLTFSerializer.cpp
Labels: bug, CR approved, QA approved

#845 Clean up GeometryCache and remove _glColor4f
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.h
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackendInput.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendInput.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendInput.cpp
  libraries/gpu/src/gpu/Batch.cpp
  libraries/gpu/src/gpu/Batch.h
  libraries/gpu/src/gpu/FrameIOKeys.h
  libraries/graphics/src/graphics/Geometry.cpp
  libraries/graphics/src/graphics/Geometry.h
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/GeometryCache.h
  libraries/render-utils/src/MeshPartPayload.cpp
Labels: bug, CR approved, QA approved

#873 Fix warnings as errors for MSVC
  CMakeLists.txt
Labels: CR approved, Windows, QA approved

#869 Change the hash salt from Vircadia to Overte
  libraries/networking/src/FingerprintUtils.cpp
Labels: CR approved, QA approved

#877 Create Application: Advanced Import functionality
  scripts/system/create/edit.js
  scripts/system/create/importEntities/html/css/importEntities.css
  scripts/system/create/importEntities/html/importEntities.html
  scripts/system/create/importEntities/html/js/importEntitiesUi.js
  scripts/system/create/qml/EditTabView.qml
  scripts/system/create/qml/EditToolsTabView.qml
Labels: CR approved, QA approved

#847 Audio Zone Properties
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/audio/AudioMixer.h
  assignment-client/src/audio/AudioMixerSlave.cpp
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixer.h
  assignment-client/src/octree/OctreeServer.cpp
  domain-server/resources/describe-settings.json
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/ZoneAudioPropertyGroup.cpp
  libraries/entities/src/ZoneAudioPropertyGroup.h
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/create/entityProperties/html/tabs/zone_audio.png
Labels: documentation, enhancement, CR approved, QA approved, server, protocol change, NLnet

#854 Fix invalid animation reference in assignment client
  assignment-client/src/avatars/ScriptableAvatar.cpp
  assignment-client/src/avatars/ScriptableAvatar.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/procedural/src/procedural/ProceduralMaterialCache.cpp
  libraries/ui/src/QmlWindowClass.cpp
Labels: bug, CR approved, needs QA

#892 Revert "Disabled texture loading for agent"
  assignment-client/src/Agent.cpp
  assignment-client/src/avatars/ScriptableAvatar.cpp
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/procedural/src/procedural/ProceduralMaterialCache.cpp
Labels: bug, needs CR, needs QA, blocker

#893 Fix previous commit for not loading textures on agent
  assignment-client/src/Agent.cpp
  assignment-client/src/avatars/ScriptableAvatar.cpp
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/procedural/src/procedural/ProceduralMaterialCache.cpp
Labels: enhancement, CR approved, QA approved

#882 Add Oculus to fullbody-enabled headsets list
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
Labels: bug, CR approved, QA approved

#863 Create App.: "Copy Dimensions" and "Paste Dimensions"
  scripts/system/create/edit.js
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: enhancement, CR approved, QA approved
