Repository overte-org/overte, pull requests merged in 2024-10, with the labels that each got.

#1152 Create app: highlight avatar entities
  scripts/system/create/entityList/entityList.js
  scripts/system/create/entityList/html/js/entityList.js
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/html/css/edit-style.css
Labels: CR approved, QA approved

#1141 Update Avatar App icons
  interface/resources/icons/tablet-icons/avatar-a.svg
  interface/resources/icons/tablet-icons/avatar-i.svg
  interface/resources/images/avatarapp/guy-in-circle.svg
  interface/resources/qml/hifi/avatarapp/AvatarAppHeader.qml
Labels: CR approved, QA approved

#1111 Text verticalAlignment, send entity property enums as uint8_t, fix text recalculating too often, fix textSize
  cmake/macros/GenerateEntityProperties.cmake
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.h
  libraries/entities/src/EntityItem.h.in
  libraries/entities/src/EntityItemProperties.cpp.in
  libraries/entities/src/EntityItemProperties.h.in
  libraries/entities/src/EntityItemProperties.txt
  libraries/entities/src/EntityItemPropertiesDocs.cpp
  libraries/entities/src/EntityPropertyFlags.h.in
  libraries/entities/src/ZoneEntityItem.cpp.in
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/OctreePacketData.h
  libraries/render-utils/src/TextRenderer3D.cpp
  libraries/render-utils/src/TextRenderer3D.h
  libraries/render-utils/src/text/Font.cpp
  libraries/render-utils/src/text/Font.h
  libraries/shared/src/AmbientOcclusionTechnique.h
  libraries/shared/src/BillboardMode.h
  libraries/shared/src/ComponentMode.h
  libraries/shared/src/EntityShape.h
  libraries/shared/src/GizmoType.h
  libraries/shared/src/MaterialMappingMode.h
  libraries/shared/src/MirrorMode.h
  libraries/shared/src/PrimitiveMode.h
  libraries/shared/src/PulseMode.h
  libraries/shared/src/RenderLayer.h
  libraries/shared/src/ShapeInfo.h
  libraries/shared/src/TextAlignment.h
  libraries/shared/src/TextEffect.h
  libraries/shared/src/TextVerticalAlignment.cpp
  libraries/shared/src/TextVerticalAlignment.h
  libraries/shared/src/TonemappingCurve.h
  libraries/shared/src/WebInputMode.h
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: documentation, enhancement, CR approved, QA approved, server, protocol change

#1155 [ Avatar App ] Fixed lingering references to now deleted QML element
  interface/resources/qml/hifi/AvatarApp.qml
  interface/resources/qml/hifi/avatarapp/AvatarAppHeader.qml
Labels: CR approved, QA approved

#1153 Place App: Weekly promoted place
  scripts/system/places/places.css
  scripts/system/places/places.html
Labels: CR approved, QA approved

#1127 Fix selfie mode movement
  interface/resources/controllers/keyboardMouse.json
Labels: CR approved, QA approved

#1123 Fix Create App not honoring menu bar actions
  scripts/system/create/edit.js
Labels: enhancement, needs CR, needs QA

#1171 Change minimum angular velocity to a lower one
  libraries/entities/src/EntityItem.cpp.in
  libraries/physics/src/ObjectMotionState.cpp
  libraries/shared/src/PhysicsHelpers.h
Labels: enhancement, CR approved, QA approved

#1164 Places App.: Persisted Maturity Filter and Default value for Newbies.
  scripts/system/places/places.html
  scripts/system/places/places.js
Labels: CR approved, QA approved

#1160 Create app: Grab and Equip
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/create/entityProperties/html/tabs/grabAndEquip.png
Labels: CR approved, QA approved

#1137 Remove Google Poly
  .eslintrc.js
  interface/src/Application.cpp
  interface/src/scripting/GooglePolyScriptingInterface.cpp
  interface/src/scripting/GooglePolyScriptingInterface.h
Labels: CR approved, QA approved

#1172 Rebuild fonts with full charset (NOT -allglyphs)
  libraries/render-utils/res/fonts/CourierPrime.arfont
  libraries/render-utils/res/fonts/InconsolataMedium.arfont
  libraries/render-utils/res/fonts/Roboto.arfont
  libraries/render-utils/res/fonts/Timeless.arfont
Labels: bug, CR approved, QA approved

#1165 Remove hifi screenshare (updated) (updated)
  CMakeLists.txt
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/MixerAvatar.h
  cmake/macros/SetPackagingParameters.cmake
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  interface/CMakeLists.txt
  interface/src/Application.cpp
  interface/src/scripting/ScreenshareScriptingInterface.cpp
  interface/src/scripting/ScreenshareScriptingInterface.h
  libraries/entities/src/EntityItemProperties.cpp.in
  libraries/entities/src/EntityItemProperties.txt
  libraries/entities/src/EntityItemPropertiesDocs.cpp
  libraries/entities/src/ZoneEntityItem.cpp.in
  libraries/networking/src/udt/PacketHeaders.h
  screenshare/.gitignore
  screenshare/CMakeLists.txt
  screenshare/README.md
  screenshare/package-lock.json
  screenshare/package.json
  screenshare/packager.js
  screenshare/src/resources/FiraSans-Regular.ttf
  screenshare/src/resources/interface.png
  screenshare/src/screenshareApp.html
  screenshare/src/screenshareApp.js
  screenshare/src/screenshareMainProcess.js
  screenshare/src/styles.css
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/edit.js
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: documentation, CR approved, QA approved, server, dependencies, protocol change

#1187 fix web entities not accepting keyboard focus
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities/src/EntityItem.h.in
Labels: bug, needs CR, needs QA, fix before release, regression

#1185 Fix stutter when an object is fading
  interface/src/Application.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/render-utils/src/AmbientOcclusionEffect.cpp
  libraries/render-utils/src/AmbientOcclusionEffect.h
  libraries/render-utils/src/AntialiasingEffect.cpp
  libraries/render-utils/src/AntialiasingEffect.h
  libraries/render-utils/src/BloomEffect.cpp
  libraries/render-utils/src/BloomEffect.h
  libraries/render-utils/src/DebugDeferredBuffer.cpp
  libraries/render-utils/src/DebugDeferredBuffer.h
  libraries/render-utils/src/FadeEffect.cpp
  libraries/render-utils/src/FadeEffect.h
  libraries/render-utils/src/FadeEffectJobs.cpp
  libraries/render-utils/src/FadeEffectJobs.h
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/HighlightEffect.cpp
  libraries/render-utils/src/HighlightEffect.h
  libraries/render-utils/src/LightClusters.cpp
  libraries/render-utils/src/LightClusters.h
  libraries/render-utils/src/RenderCommonTask.cpp
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/StencilMaskPass.cpp
  libraries/render-utils/src/StencilMaskPass.h
  libraries/render-utils/src/SubsurfaceScattering.cpp
  libraries/render-utils/src/SubsurfaceScattering.h
  libraries/render-utils/src/SurfaceGeometryPass.cpp
  libraries/render-utils/src/SurfaceGeometryPass.h
  libraries/render-utils/src/ToneMapAndResampleTask.h
  libraries/render-utils/src/VelocityBufferPass.cpp
  libraries/render-utils/src/VelocityBufferPass.h
  libraries/render-utils/src/ZoneRenderer.cpp
  libraries/render-utils/src/ZoneRenderer.h
  libraries/render/src/render/BlurTask.cpp
  libraries/render/src/render/BlurTask.h
  libraries/render/src/render/DrawSceneOctree.cpp
  libraries/render/src/render/DrawSceneOctree.h
  libraries/render/src/render/DrawStatus.cpp
  libraries/render/src/render/DrawStatus.h
  libraries/render/src/render/DrawTask.cpp
  libraries/render/src/render/DrawTask.h
  libraries/render/src/render/Scene.cpp
  libraries/task/src/task/Task.h
  scripts/developer/utilities/lib/jet/jet.js
Labels: bug, needs CR, needs QA, fix before release, regression

#1195 fix density max typo
  libraries/entities/src/EntityItemProperties.txt
Labels: bug, needs CR, needs QA, fix before release, regression

#1196 Fix ArmoredChat quick_message qml dialog colors on light theme systems
  scripts/communityScripts/armored-chat/armored_chat.qml
  scripts/communityScripts/armored-chat/armored_chat_quick_message.qml
Labels: CR approved, QA approved
