Repository overte-org/overte, pull requests merged in 2024-07, with the labels that each got.

#1061 Increase default vertical FOV
  libraries/shared/src/ViewFrustum.h
  scripts/system/libraries/WebTablet.js
Labels: enhancement, CR approved

#1065 Fix crash in setCrashReporterEnabled
  libraries/networking/src/crash-handler/CrashHandlerBackend_Crashpad.cpp
Labels: CR approved

#1064 Always enable crash reporting.
  .github/workflows/linux_server_build.yml
Labels: CR approved

#1055 Fix mtoon issue on GLES
  libraries/graphics/src/graphics/MaterialTextures.slh
Labels: bug, CR approved, QA approved

#1063 Update make-rpm-server to remove `-` characters.
  pkg-scripts/make-rpm-server
Labels: server

#1071 Fix GHA building hundreds of servers
  .github/workflows/linux_server_build.yml
Labels: CR approved, server

#1077 Remove remnants of RELEASE_NAME.
  cmake/macros/GenerateInstallers.cmake
  interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
Labels: CR approved

#1073 Update VCPKG on Windows, so it can find newer versions of Visual Studio.
  hifi_vcpkg.py
Labels: CR approved

#1072 Fix broken upload paths for RPM distributions.
  .github/workflows/linux_server_build.yml
Labels: CR approved, fix before release

#961 Replace Floofchat with ArmoredChat
  script-archive/floofChat/FloofChat.html
  script-archive/floofChat/FloofChat.js
  script-archive/floofChat/FloofChat.qml
  script-archive/floofChat/chat.png
  script-archive/floofChat/css/FloofChat.css
  script-archive/floofChat/css/materialize.css
  script-archive/floofChat/js/materialize.min.js
  script-archive/floofChat/resources/bubblepop.wav
  script-archive/systemChat/ChatPage.html
  script-archive/systemChat/chat.js
  scripts/communityScripts/armored-chat/README.md
  scripts/communityScripts/armored-chat/armored_chat.js
  scripts/communityScripts/armored-chat/armored_chat.qml
  scripts/communityScripts/armored-chat/armored_chat_quick_message.qml
  scripts/communityScripts/armored-chat/img/icon_black.png
  scripts/communityScripts/armored-chat/img/icon_white.png
  scripts/communityScripts/armored-chat/img/ui/send.svg
  scripts/communityScripts/armored-chat/img/ui/send_black.png
  scripts/communityScripts/armored-chat/img/ui/send_white.png
  scripts/communityScripts/armored-chat/img/ui/settings_black.png
  scripts/communityScripts/armored-chat/img/ui/settings_white.png
  scripts/communityScripts/armored-chat/img/ui/social_black.png
  scripts/communityScripts/armored-chat/img/ui/social_white.png
  scripts/communityScripts/armored-chat/img/ui/world_black.png
  scripts/communityScripts/armored-chat/img/ui/world_white.png
  scripts/defaultScripts.js
Labels: CR approved, QA approved

#1004 MouseLook.js refactor
  scripts/system/controllers/mouseLook.js
  scripts/system/inspect.js
Labels: CR approved, QA approved

#1081 Fix mouselook ignoring setting.
  scripts/system/controllers/mouseLook.js
Labels: CR approved, QA approved

#1086 Fix controllerScripts uncaught exception.
  scripts/system/controllers/controllerScripts.js
Labels: CR approved

#1069 Remove (deprecated) attachments
  assignment-client/src/avatars/ScriptableAvatar.h
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/AvatarBookmarks.cpp
  interface/src/AvatarBookmarks.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/OtherAvatar.cpp
  interface/src/ui/DialogsManager.h
  interface/src/ui/ModelsBrowser.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars-renderer/src/avatars-renderer/ScriptAvatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/ScriptAvatarData.cpp
  libraries/avatars/src/ScriptAvatarData.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/model-serializers/src/FSTReader.cpp
  libraries/model-serializers/src/FSTReader.h
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/recording/src/recording/RecordingScriptingInterface.cpp
  libraries/recording/src/recording/RecordingScriptingInterface.h
  libraries/render-utils/src/SoftAttachmentModel.cpp
  libraries/render-utils/src/SoftAttachmentModel.h
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
Labels: documentation, CR approved, QA approved, server, protocol change, NLnet

#1087 Dump protocol data
  interface/src/main.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
Labels: CR approved

#1050 Zone properties for tonemapping and ambient occlusion
  interface/src/scripting/RenderScriptingInterface.h
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.h
  libraries/entities/src/AmbientOcclusionPropertyGroup.cpp
  libraries/entities/src/AmbientOcclusionPropertyGroup.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/TonemappingPropertyGroup.cpp
  libraries/entities/src/TonemappingPropertyGroup.h
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  libraries/graphics/src/graphics/AmbientOcclusion.h
  libraries/graphics/src/graphics/Tonemapping.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/OctreePacketData.h
  libraries/render-utils/src/AmbientOcclusionEffect.cpp
  libraries/render-utils/src/AmbientOcclusionEffect.h
  libraries/render-utils/src/AmbientOcclusionStage.cpp
  libraries/render-utils/src/AmbientOcclusionStage.h
  libraries/render-utils/src/AssembleLightingStageTask.cpp
  libraries/render-utils/src/AssembleLightingStageTask.h
  libraries/render-utils/src/BackgroundStage.cpp
  libraries/render-utils/src/BloomStage.cpp
  libraries/render-utils/src/BloomStage.h
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DeferredLightingEffect.h
  libraries/render-utils/src/HazeStage.cpp
  libraries/render-utils/src/LightStage.cpp
  libraries/render-utils/src/LightingModel.h
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/ToneMapAndResampleTask.cpp
  libraries/render-utils/src/ToneMapAndResampleTask.h
  libraries/render-utils/src/TonemappingStage.cpp
  libraries/render-utils/src/TonemappingStage.h
  libraries/render-utils/src/UpdateSceneTask.cpp
  libraries/render-utils/src/ZoneRenderer.cpp
  libraries/render-utils/src/toneMapping.slf
  libraries/shared/src/AmbientOcclusionTechnique.cpp
  libraries/shared/src/AmbientOcclusionTechnique.h
  libraries/shared/src/TonemappingCurve.cpp
  libraries/shared/src/TonemappingCurve.h
  scripts/developer/utilities/render/ambientOcclusionPass.qml
  scripts/developer/utilities/render/luci/ToneMapping.qml
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/create/entityProperties/html/tabs/zone_ambient_occlusion.png
  scripts/system/create/entityProperties/html/tabs/zone_tonemapping.png
Labels: documentation, enhancement, help wanted, CR approved, needs QA, server, protocol change, NLnet

#1091 Create App: Material Assistant: Add Mtoon, Shader_simple, missing PBR properties and bug fixes.
  scripts/system/create/entityProperties/html/entityProperties.html
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/create/entityProperties/html/js/materialAssistant.js
  scripts/system/html/css/materialAssistant.css
Labels: CR approved, QA approved

#1093 Fix login failure handling and improve logging.
  interface/resources/qml/LoginDialog/LoggingInBody.qml
  libraries/networking/src/AccountManager.cpp
Labels: CR approved
