Repository overte-org/overte, pull requests merged in 2024-11, with the labels that each got.

#1215 Fix missing properties in Script API
  libraries/script-engine/src/ScriptManager.h
  libraries/script-engine/src/ScriptManagerScriptingInterface.h
Labels: bug, CR approved

#1210 Fix ArmoredChat scrolling
  scripts/communityScripts/armored-chat/armored_chat.js
  scripts/communityScripts/armored-chat/armored_chat.qml
Labels: enhancement, CR approved, QA approved

#1202 Create App.: Add "Paste" button for NewSoundDialog QML.
  scripts/system/create/qml/NewSoundDialog.qml
Labels: CR approved, QA approved

#1224 Fix lack of entityHostType property
  libraries/entities/src/EntityItem.cpp.in
Labels: bug, CR approved, QA approved, fix before release

#1230 Fix access-after-delete on leaving domain with entity scripts
  assignment-client/src/scripts/EntityScriptServer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/script-engine/src/ScriptManager.cpp
  libraries/script-engine/src/ScriptManager.h
Labels: bug, CR approved, needs QA

#1234 fix fade out not working in forward rendering
  libraries/render-utils/src/FadeEffect.cpp
  libraries/render-utils/src/FadeEffect.h
  libraries/render-utils/src/FadeEffectJobs.cpp
  libraries/render-utils/src/FadeEffectJobs.h
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderViewTask.cpp
Labels: bug, CR approved, QA approved, fix before release

#1236 Fix access-after-delete during entity script engine cleanup
  libraries/script-engine/src/v8/ScriptEngineDebugFlags.h
  libraries/script-engine/src/v8/ScriptEngineV8.cpp
  libraries/script-engine/src/v8/ScriptEngineV8.h
  libraries/script-engine/src/v8/ScriptObjectV8Proxy.cpp
  libraries/script-engine/src/v8/ScriptObjectV8Proxy.h
Labels: bug, CR approved, QA approved, fix before release

#1251 Fix script-related crashes on exiting a domain
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/script-engine/src/ScriptManager.cpp
  libraries/script-engine/src/ScriptManager.h
Labels: bug, CR approved, fix before release

#1250 Added sounds to all incoming chat messages
  scripts/communityScripts/notificationCore/notificationCore.js
  scripts/communityScripts/notificationCore/resources/click.wav
Labels: enhancement, needs CR, QA approved

#1237 Update privacy policy link
  interface/resources/qml/LoginDialog/SignUpBody.qml
  interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml
Labels: bug, enhancement, needs CR, QA approved

#1203 ArmoredChat notifications on join and leave
  scripts/communityScripts/armored-chat/armored_chat.js
  scripts/communityScripts/armored-chat/armored_chat.qml
Labels: enhancement, CR approved, QA approved

#1204 Add a label to the Pal application 'displayname' field
  interface/resources/qml/hifi/Pal.qml
Labels: enhancement, CR approved, QA approved

#1226 possible fix for missing jsdoc
  tools/jsdoc/plugins/hifi.js
Labels: bug, documentation, fix before release

#1241 Change ArmoredChat timestamps to use real timestamps
  scripts/communityScripts/armored-chat/armored_chat.js
  scripts/communityScripts/armored-chat/armored_chat.qml
Labels: enhancement, CR approved, QA approved

#1176 remove unnecessary fullscreen pass when haze is off/disabled
  libraries/graphics/src/graphics/Haze.cpp
  libraries/graphics/src/graphics/Haze.h
  libraries/render-utils/src/DrawHaze.cpp
  libraries/render-utils/src/Haze.slf
Labels: enhancement, CR approved, QA approved

#1177 Templated render stages
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/render-utils/src/AmbientOcclusionEffect.cpp
  libraries/render-utils/src/AmbientOcclusionStage.cpp
  libraries/render-utils/src/AmbientOcclusionStage.h
  libraries/render-utils/src/AssembleLightingStageTask.cpp
  libraries/render-utils/src/BackgroundStage.cpp
  libraries/render-utils/src/BackgroundStage.h
  libraries/render-utils/src/BloomEffect.cpp
  libraries/render-utils/src/BloomStage.cpp
  libraries/render-utils/src/BloomStage.h
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DrawHaze.cpp
  libraries/render-utils/src/FadeEffect.cpp
  libraries/render-utils/src/FadeEffectJobs.cpp
  libraries/render-utils/src/HazeStage.cpp
  libraries/render-utils/src/HazeStage.h
  libraries/render-utils/src/HighlightEffect.cpp
  libraries/render-utils/src/LightClusters.cpp
  libraries/render-utils/src/LightClusters.h
  libraries/render-utils/src/LightPayload.cpp
  libraries/render-utils/src/LightStage.cpp
  libraries/render-utils/src/LightStage.h
  libraries/render-utils/src/RenderCommonTask.cpp
  libraries/render-utils/src/RenderCommonTask.h
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/SubsurfaceScattering.cpp
  libraries/render-utils/src/ToneMapAndResampleTask.cpp
  libraries/render-utils/src/TonemappingStage.cpp
  libraries/render-utils/src/TonemappingStage.h
  libraries/render-utils/src/ZoneRenderer.cpp
  libraries/render/src/render/DrawStatus.cpp
  libraries/render/src/render/HighlightStage.cpp
  libraries/render/src/render/HighlightStage.h
  libraries/render/src/render/HighlightStyle.h
  libraries/render/src/render/Scene.cpp
  libraries/render/src/render/Stage.cpp
  libraries/render/src/render/Stage.h
  libraries/render/src/render/StageSetup.h
  libraries/render/src/render/TransitionStage.cpp
  libraries/render/src/render/TransitionStage.h
Labels: CR approved, QA approved

#1178 support more procedural shader uniform types, including arrays
  libraries/gpu/src/gpu/Batch.h
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/procedural/src/procedural/Procedural.h
Labels: enhancement, CR approved, QA approved

#1220 Fixed Camera Sensitivity setting not saving
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: bug, CR approved, QA approved
