Repository overte-org/overte, pull requests merged in 2024-09, with the labels that each got.

#1089 Remove unused onFirstRun.js
  scripts/defaultScripts.js
  scripts/system/onFirstRun.js
Labels: CR approved, QA approved

#1084 [Armored Chat] Change the 'open in new window' character.
  scripts/communityScripts/armored-chat/armored_chat.qml
Labels: CR approved, QA approved

#1078 Sanitize notificationCore text to prevent XSS
  scripts/communityScripts/notificationCore/notificationCore.js
Labels: enhancement, CR approved, QA approved

#1085 Improve model load priority
  interface/resources/qml/+android_interface/Stats.qml
  interface/resources/qml/Stats.qml
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/OtherAvatar.cpp
  interface/src/avatar/OtherAvatar.h
  interface/src/scripting/AccountServicesScriptingInterface.cpp
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
  libraries/animation/src/AnimNodeLoader.cpp
  libraries/audio/src/SoundCache.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/material-networking/src/material-networking/TextureCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-networking/src/model-networking/ModelCache.h
  libraries/model-serializers/src/FSTReader.cpp
  libraries/model-serializers/src/FSTReader.h
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/ResourceCache.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: documentation, enhancement, CR approved, QA approved, server, protocol change, NLnet

#1138 fix accidentally clearing url fields when you don't have view permission
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: bug, CR approved, QA approved
