Repository overte-org/overte, pull requests merged in 2024-05, with the labels that each got.

#152 add canViewAssetURLs domain permissions
  domain-server/resources/describe-settings.json
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServerSettingsManager.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/ScriptAvatarData.cpp
  libraries/entities/src/AmbientLightPropertyGroup.cpp
  libraries/entities/src/AmbientLightPropertyGroup.h
  libraries/entities/src/AnimationPropertyGroup.cpp
  libraries/entities/src/AnimationPropertyGroup.h
  libraries/entities/src/BloomPropertyGroup.cpp
  libraries/entities/src/BloomPropertyGroup.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemPropertiesMacros.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/entities/src/GrabPropertyGroup.cpp
  libraries/entities/src/GrabPropertyGroup.h
  libraries/entities/src/HazePropertyGroup.cpp
  libraries/entities/src/HazePropertyGroup.h
  libraries/entities/src/KeyLightPropertyGroup.cpp
  libraries/entities/src/KeyLightPropertyGroup.h
  libraries/entities/src/PropertyGroup.h
  libraries/entities/src/PulsePropertyGroup.cpp
  libraries/entities/src/PulsePropertyGroup.h
  libraries/entities/src/RingGizmoPropertyGroup.cpp
  libraries/entities/src/RingGizmoPropertyGroup.h
  libraries/entities/src/SkyboxPropertyGroup.cpp
  libraries/entities/src/SkyboxPropertyGroup.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/Node.h
  libraries/networking/src/NodePermissions.cpp
  libraries/networking/src/NodePermissions.h
  scripts/system/create/edit.js
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: enhancement, CR approved, QA approved, Security, server, fix before release

#950 Fix C++20 warnings
  interface/src/LODManager.cpp
  libraries/gpu/src/gpu/Batch.h
  libraries/gpu/src/gpu/Buffer.h
  libraries/shared/src/SimpleMovingAverage.h
Labels: CR approved, QA approved

#955 Fix access check in getSkeletonModelURLFromScript
  libraries/avatars/src/AvatarData.cpp
Labels: bug, CR approved, QA approved

#960 SimplifiedUI adjustemnts
  interface/resources/qml/hifi/simplifiedUI/helpApp/faq/HelpFAQ.qml
  interface/resources/qml/hifi/simplifiedUI/helpApp/support/HelpSupport.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/dev/Dev.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/general/General.qml
  interface/resources/qml/hifi/simplifiedUI/simplifiedControls/Button.qml
  scripts/simplifiedUI/ui/simplifiedUI.js
Labels: CR approved

#978 Fixed locale problems with cgltf.h
  libraries/model-serializers/src/GLTFSerializer.h
Labels: bug, CR approved, QA approved, fix before release

#964 Fixed script signal proxy crashes
  libraries/script-engine/src/v8/ScriptObjectV8Proxy.cpp
  libraries/script-engine/src/v8/ScriptObjectV8Proxy.h
Labels: bug, CR approved, needs QA, fix before release

#966 Add Ubuntu 24.04 to server packaging
  .github/workflows/linux_server_build.yml
  cmake/ports/node/portfile.cmake
  tools/ci-scripts/deb_package/Dockerfile_build_ubuntu-24.04
Labels: CR approved, server

#959 Fixed deadlocks in Recording API
  assignment-client/src/AgentScriptingInterface.h
  libraries/recording/src/recording/RecordingScriptingInterface.cpp
  libraries/recording/src/recording/RecordingScriptingInterface.h
Labels: bug, CR approved, QA approved, fix before release
