Repository overte-org/overte, pull requests merged in 2024-02, with the labels that each got.

#805 MToon materials
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableImageEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.h
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/graphics-scripting/src/graphics-scripting/Forward.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.cpp
  libraries/graphics/src/graphics/Material.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/graphics/src/graphics/Material.slh
  libraries/graphics/src/graphics/MaterialTextures.slh
  libraries/graphics/src/graphics/ShaderConstants.h
  libraries/procedural/src/procedural/ProceduralMaterialCache.cpp
  libraries/procedural/src/procedural/ProceduralMaterialCache.h
  libraries/procedural/src/procedural/ReferenceMaterial.cpp
  libraries/procedural/src/procedural/ReferenceMaterial.h
  libraries/render-utils/src/GlobalLight.slh
  libraries/render-utils/src/HighlightEffect.cpp
  libraries/render-utils/src/HighlightEffect.h
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/RenderShadowTask.cpp
  libraries/render-utils/src/model.slf
  libraries/render-utils/src/model.slv
  libraries/render-utils/src/render-utils/model.slp
  libraries/render/src/render/HighlightStyle.h
  libraries/render/src/render/Item.cpp
  libraries/render/src/render/Item.h
  libraries/render/src/render/RenderFetchCullSortTask.cpp
  libraries/render/src/render/RenderFetchCullSortTask.h
  libraries/render/src/render/Scene.cpp
  libraries/render/src/render/Scene.h
  libraries/render/src/render/Selection.h
  libraries/render/src/render/ShapePipeline.h
Labels: documentation, enhancement, CR approved, QA approved

#813 Add a way to get VCPKG path and hash ID
  hifi_qt.py
  hifi_vcpkg.py
  prebuild.py
Labels: CR approved

#812 Linux server gha update
  .github/workflows/linux_server_build.yml
  hifi_vcpkg.py
  tools/ci-scripts/deb_package/Dockerfile_build_ubuntu-18.04
  tools/ci-scripts/rpm_package/Dockerfile_build_fedora-39
Labels: server

#673 Entity script logging for script editor
  assignment-client/src/scripts/EntityScriptServer.cpp
  assignment-client/src/scripts/EntityScriptServer.h
  interface/src/Application.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities/src/EntityScriptServerLogClient.cpp
  libraries/entities/src/EntityScriptServerLogClient.h
  libraries/script-engine/src/ConsoleScriptingInterface.cpp
  libraries/script-engine/src/ScriptContext.h
  libraries/script-engine/src/ScriptEngines.cpp
  libraries/script-engine/src/ScriptEngines.h
  libraries/script-engine/src/ScriptManager.cpp
  libraries/script-engine/src/ScriptManager.h
  libraries/script-engine/src/ScriptManagerScriptingInterface.cpp
  libraries/script-engine/src/ScriptManagerScriptingInterface.h
  libraries/script-engine/src/ScriptMessage.cpp
  libraries/script-engine/src/ScriptMessage.h
  libraries/script-engine/src/v8/ScriptContextV8Wrapper.cpp
  libraries/script-engine/src/v8/ScriptContextV8Wrapper.h
  libraries/script-engine/src/v8/ScriptEngineV8.cpp
  libraries/script-engine/src/v8/ScriptEngineV8.h
  libraries/script-engine/src/v8/ScriptObjectV8Proxy.cpp
  libraries/script-engine/src/v8/ScriptValueV8Wrapper.cpp
Labels: CR approved, QA approved

#819 Fix entity density not setting and not updating for motion states
  interface/src/avatar/AvatarMotionState.cpp
  interface/src/avatar/DetailedMotionState.cpp
  libraries/entities/src/EntityItemPropertiesDefaults.h
  libraries/physics/src/EntityMotionState.cpp
  libraries/physics/src/ObjectMotionState.cpp
Labels: bug, needs CR, QA approved

#815 Add keyboard modifiers to entity pointer events
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
Labels: bug, needs CR, needs QA

#806 Create app: RenderWithZones Manager
  scripts/system/create/edit.js
  scripts/system/create/entityList/entityList.js
  scripts/system/create/entityList/html/entityList.html
  scripts/system/create/entityList/html/js/entityList.js
  scripts/system/create/modules/renderWithZonesManager.html
  scripts/system/create/modules/renderWithZonesManager.js
Labels: CR approved, QA approved

#835 glTF importer using cgltf library
  cmake/ports/cgltf/portfile.cmake
  cmake/ports/cgltf/vcpkg.json
  cmake/ports/hifi-deps/CONTROL
  libraries/model-networking/src/model-networking/ModelLoader.cpp
  libraries/model-serializers/src/GLTFSerializer.cpp
  libraries/model-serializers/src/GLTFSerializer.h
  tests/model-serializers/CMakeLists.txt
  tests/model-serializers/src/ModelSerializersTests.cpp
Labels: bug, CR approved, QA approved

#837 Remove debug print with URL from ModelLoader
  libraries/model-networking/src/model-networking/ModelLoader.cpp
Labels: bug, needs CR
