Repository overte-org/overte, pull requests merged in 2024-04, with the labels that each got.

#889 Ability to smooth model animations
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities/src/AnimationPropertyGroup.cpp
  libraries/entities/src/AnimationPropertyGroup.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: documentation, enhancement, CR approved, QA approved, server, protocol change, NLnet

#868 Add qByteArray to script value conversion
  libraries/script-engine/src/ScriptManagerScriptingInterface.cpp
  libraries/script-engine/src/ScriptManagerScriptingInterface.h
  libraries/script-engine/src/ScriptValueUtils.cpp
  libraries/script-engine/src/v8/FastScriptValueUtils.cpp
  libraries/script-engine/src/v8/FastScriptValueUtils.h
Labels: enhancement, CR approved, QA approved, fix before release

#899 Custom refresh rate profile
  interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
  interface/src/RefreshRateManager.cpp
  interface/src/RefreshRateManager.h
  interface/src/scripting/PerformanceScriptingInterface.cpp
  interface/src/scripting/PerformanceScriptingInterface.h
  interface/src/ui/PreferencesDialog.cpp
Labels: documentation, enhancement, CR approved, QA approved, fix before release

#935 conversionPenaltyScore should accumulate
  libraries/script-engine/src/v8/ScriptObjectV8Proxy.cpp
Labels: bug, CR approved, QA approved, v8, NLnet

#927 Fix getEntityProperties for group properties + keylight direction
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesMacros.h
Labels: bug, CR approved, QA approved, fix before release

#887 Added simple protection for avatar URL
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/PermissionChecker.java
  interface/resources/qml/hifi/dialogs/security/ScriptSecurity.qml
  interface/src/Application.cpp
  interface/src/AvatarBookmarks.cpp
  interface/src/AvatarBookmarks.h
  interface/src/CrashRecoveryHandler.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/scripting/SettingsScriptingInterface.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/ScriptAvatarData.cpp
  libraries/networking/src/NetworkingConstants.h
  libraries/script-engine/src/ScriptManager.cpp
  libraries/script-engine/src/ScriptManager.h
  libraries/script-engine/src/ScriptPermissions.cpp
  libraries/script-engine/src/ScriptPermissions.h
  libraries/shared/src/SettingHandle.cpp
  libraries/shared/src/SettingHandle.h
  tools/nitpick/AppDataHighFidelity/Interface.json
Labels: CR approved, QA approved, fix before release

#884 GPU Particles
  interface/resources/shaders/proceduralParticleSwarmRender.frag
  interface/resources/shaders/proceduralParticleSwarmRender.vert
  interface/resources/shaders/proceduralParticleSwarmUpdate.frag
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.h
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.h
  libraries/entities-renderer/src/RenderableProceduralParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderableProceduralParticleEffectEntityItem.h
  libraries/entities-renderer/src/entities-renderer/proceduralParticle.slp
  libraries/entities-renderer/src/proceduralParticle.slf
  libraries/entities-renderer/src/proceduralParticle.slv
  libraries/entities-renderer/src/proceduralParticleUpdate.slf
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/EntityTreeElement.cpp
  libraries/entities/src/EntityTypes.cpp
  libraries/entities/src/EntityTypes.h
  libraries/entities/src/ProceduralParticleEffectEntityItem.cpp
  libraries/entities/src/ProceduralParticleEffectEntityItem.h
  libraries/gpu/src/gpu/Transform.slh
  libraries/networking/src/udt/PacketHeaders.h
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/procedural/src/procedural/Procedural.h
  libraries/procedural/src/procedural/ProceduralParticleCommon.slh
  libraries/procedural/src/procedural/ShaderConstants.h
  libraries/render-utils/src/RenderCommonTask.cpp
  libraries/render-utils/src/RenderCommonTask.h
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render/src/render/FilterTask.cpp
  libraries/render/src/render/FilterTask.h
  libraries/render/src/render/Item.cpp
  libraries/render/src/render/Item.h
  libraries/render/src/render/RenderFetchCullSortTask.cpp
  libraries/render/src/render/RenderFetchCullSortTask.h
  libraries/render/src/render/Scene.h
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/edit.js
  scripts/system/create/entityList/html/js/entityList.js
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/create/entityProperties/html/tabs/particles_procedural.png
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
  scripts/system/create/qml/NewMaterialDialog.qml
  scripts/system/create/qml/NewModelDialog.qml
  scripts/system/create/qml/NewParticleDialog.qml
  scripts/system/create/qml/NewParticleWindow.qml
  scripts/system/create/qml/NewPolyVoxDialog.qml
  scripts/system/html/css/edit-style.css
  scripts/system/html/js/includes.js
Labels: documentation, enhancement, CR approved, QA approved, server, protocol change, NLnet

#936 support VRMC_materials_mtoon and KHR_materials_unlit
  interface/src/avatar/AvatarDoctor.cpp
  interface/src/avatar/AvatarProject.cpp
  libraries/baking/src/MaterialBaker.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/hfm/src/hfm/HFM.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-serializers/CMakeLists.txt
  libraries/model-serializers/src/GLTFSerializer.cpp
  libraries/procedural/src/procedural/ProceduralMaterialCache.cpp
  libraries/procedural/src/procedural/ProceduralMaterialCache.h
Labels: CR approved, QA approved, fix before release, glTF, NLnet

#853 Move helper script engines to their own threads
  assignment-client/src/avatars/ScriptableAvatar.cpp
  assignment-client/src/avatars/ScriptableAvatar.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/baking/src/MaterialBaker.cpp
  libraries/baking/src/MaterialBaker.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/script-engine/src/HelperScriptEngine.cpp
  libraries/script-engine/src/HelperScriptEngine.h
Labels: CR approved, QA approved, fix before release
