Repository overte-org/overte, pull requests merged in 2024-06, with the labels that each got.

#991 Fix tests
  tests/shared/src/BitVectorHelperTests.cpp
  tests/shared/src/FileCacheTests.cpp
  tests/shared/src/MovingPercentileTests.cpp
Labels: CR approved

#1003 Fix some warnings
  CMakeLists.txt
  interface/src/Application.cpp
  interface/src/LODManager.cpp
  interface/src/scripting/WindowScriptingInterface.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/graphics-scripting/CMakeLists.txt
  libraries/render-utils/src/text/Font.cpp
  libraries/script-engine/src/AssetScriptingInterface.cpp
  libraries/script-engine/src/ConsoleScriptingInterface.cpp
  libraries/script-engine/src/Mat4.cpp
  libraries/script-engine/src/Quat.cpp
  libraries/script-engine/src/ScriptUUID.cpp
  libraries/script-engine/src/Vec3.cpp
  libraries/script-engine/src/v8/ScriptEngineV8.cpp
  libraries/shared/src/PortableHighResolutionClock.h
  libraries/shared/src/shared/WebRTC.h
  libraries/ui/CMakeLists.txt
  libraries/ui/src/ui/OffscreenQmlSurface.cpp
  plugins/JSAPIExample/src/JSAPIExample.cpp
  tools/nitpick/src/TestRunnerDesktop.cpp
  tools/nitpick/src/TestRunnerDesktop.h
Labels: needs CR, NLnet

#1006 Fix Locker issue in RecordingScriptingInterface
  libraries/recording/src/recording/RecordingScriptingInterface.cpp
  libraries/recording/src/recording/RecordingScriptingInterface.h
  libraries/script-engine/src/AssetScriptingInterface.cpp
Labels: bug, CR approved, fix before release

#1010 Add Fedora 40 servers
  .github/workflows/linux_server_build.yml
  pkg-scripts/make-rpm-server
  pkg-scripts/overte-server.spec
  tools/ci-scripts/rpm_package/Dockerfile_build_fedora-40
Labels: needs CR, server

#1007 Fix more warnings
  interface/src/avatar/MyAvatar.cpp
  libraries/graphics/src/graphics/Geometry.cpp
  libraries/model-serializers/src/GLTFSerializer.cpp
  libraries/model-serializers/src/GLTFSerializer.h
  libraries/render-utils/src/Model.cpp
  libraries/render/src/render/FilterTask.cpp
  libraries/render/src/render/Item.h
  libraries/script-engine/src/ScriptManager.cpp
  libraries/script-engine/src/v8/FastScriptValueUtils.cpp
  libraries/script-engine/src/v8/ScriptObjectV8Proxy.cpp
  libraries/shared/src/BlendshapeConstants.h
Labels: CR approved, NLnet

#1013 Fix new debug build warning
  interface/src/avatar/MyAvatar.cpp
  libraries/physics/src/CharacterController.h
Labels: needs CR

#937 Text Entity Improvements
  cmake/ports/artery-font-format/disable-checksum.patch
  cmake/ports/artery-font-format/portfile.cmake
  cmake/ports/artery-font-format/vcpkg.json
  cmake/ports/hifi-deps/CONTROL
  libraries/entities/src/EntityItemProperties.cpp
  libraries/render-utils/res/fonts/CourierPrime-OFL.txt
  libraries/render-utils/res/fonts/CourierPrime.arfont
  libraries/render-utils/res/fonts/CourierPrime.license
  libraries/render-utils/res/fonts/CourierPrime.sdff
  libraries/render-utils/res/fonts/Inconsolata-OFL.txt
  libraries/render-utils/res/fonts/InconsolataMedium.arfont
  libraries/render-utils/res/fonts/InconsolataMedium.sdff
  libraries/render-utils/res/fonts/Roboto-LICENSE.txt
  libraries/render-utils/res/fonts/Roboto.arfont
  libraries/render-utils/res/fonts/Roboto.sdff
  libraries/render-utils/res/fonts/Timeless.arfont
  libraries/render-utils/res/fonts/Timeless.sdff
  libraries/render-utils/res/fonts/fonts.qrc
  libraries/render-utils/src/sdf_text3D.slf
  libraries/render-utils/src/sdf_text3D.slh
  libraries/render-utils/src/sdf_text3D.slv
  libraries/render-utils/src/text/Font.cpp
  libraries/render-utils/src/text/Font.h
  libraries/render-utils/src/text/Glyph.cpp
  libraries/render-utils/src/text/Glyph.h
  scripts/system/create/assets/data/createAppTooltips.json
Labels: bug, documentation, enhancement, CR approved, QA approved, NLnet

#1025 Fix RPM packaging
  pkg-scripts/overte-server.spec
Labels: server

#1024 Temporary fix for some script messages not being transmitted
  libraries/script-engine/src/ScriptManager.cpp
Labels: bug, CR approved, QA approved

#1021 GitHub Action Runner auto-scaling
  .github/workflows/linux_server_build.yml
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
Labels: server

#1022 GitHub Actions server release builds
  .github/workflows/linux_server_build.yml
Labels: CR approved

#1037 Fix unhandled std::bad_weak_ptr
  libraries/script-engine/src/ScriptManager.cpp
Labels: bug, CR approved

#1032 Update Ubuntu 20.04 amd64 Qt package
  hifi_qt.py
  tools/qt-builder/Dockerfile_Ubuntu_20.04_Qt5
Labels: CR approved, QA approved

#1041 Unlit Shapes
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: documentation, enhancement, needs CR, QA approved, server, protocol change

#1029 Fix long messages in Entity script log
  libraries/entities/src/EntityScriptServerLogClient.cpp
  libraries/script-engine/src/ScriptEngines.h
Labels: bug, needs CR, QA approved

#1039 Remove RELEASE_NAME
  BUILD.md
  INSTALLER.md
  cmake/macros/SetPackagingParameters.cmake
  cmake/templates/BuildInfo.h.in
  interface/src/AboutUtil.cpp
  interface/src/AboutUtil.h
  interface/src/Application.cpp
Labels: CR approved

#1043 Ambient Light Color
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities/src/AmbientLightPropertyGroup.cpp
  libraries/entities/src/AmbientLightPropertyGroup.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityPropertyFlags.h
  libraries/graphics/src/graphics/Light.cpp
  libraries/graphics/src/graphics/Light.h
  libraries/graphics/src/graphics/Light.slh
  libraries/graphics/src/graphics/skybox.slf
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/GlobalLight.slh
  libraries/render-utils/src/LightAmbient.slh
  libraries/render-utils/src/zone_drawAmbient.slf
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: documentation, enhancement, CR approved, QA approved, server, protocol change, NLnet

#1014 Wiggly lasers
  interface/src/Application.cpp
  interface/src/raypick/LaserPointer.cpp
  interface/src/raypick/LaserPointer.h
  interface/src/raypick/ParabolaPointer.cpp
  interface/src/raypick/PathPointer.cpp
  interface/src/raypick/PathPointer.h
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/PickScriptingInterface.h
  interface/src/raypick/PointerScriptingInterface.cpp
  interface/src/raypick/PointerScriptingInterface.h
  interface/src/raypick/RayPick.cpp
  interface/src/raypick/RayPick.h
  interface/src/raypick/StylusPointer.cpp
  interface/src/ui/PreferencesDialog.cpp
  libraries/pointers/src/Pick.h
  libraries/pointers/src/PickManager.cpp
  libraries/pointers/src/PickManager.h
  libraries/pointers/src/Pointer.cpp
  libraries/pointers/src/Pointer.h
  libraries/pointers/src/PointerManager.cpp
  libraries/pointers/src/PointerManager.h
  libraries/shared/src/RegisteredMetaTypes.h
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/libraries/pointersUtils.js
Labels: documentation, enhancement, CR approved, QA approved, NLnet

#1046 Allow events from VR keyboard to overlay UI
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/ui/Keyboard.cpp
  interface/src/ui/Keyboard.h
Labels: enhancement, needs CR, QA approved

#1049 Cut back on master builds.
  .github/workflows/linux_server_build.yml
  .github/workflows/master_build.yml
Labels: CR approved
