Repository overte-org/overte, pull requests merged in 2024-08, with the labels that each got.

#1058 Custom shader fallbacks
  interface/resources/shaders/errorShader.frag
  interface/resources/shaders/errorSkyboxShader.frag
  interface/src/Menu.cpp
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/procedural/src/procedural/Procedural.h
  libraries/procedural/src/procedural/ProceduralSkybox.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
Labels: enhancement, CR approved, needs QA, NLnet

#1053 Graphics settings
  interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
  interface/src/Menu.cpp
  interface/src/PerformanceManager.cpp
  interface/src/scripting/RenderScriptingInterface.cpp
  interface/src/scripting/RenderScriptingInterface.h
  libraries/render-utils/src/DrawHaze.cpp
  libraries/render-utils/src/DrawHaze.h
  libraries/render-utils/src/Haze.slf
  libraries/render-utils/src/LightingModel.h
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/render-utils/haze.slp
Labels: documentation, enhancement, work in progress, CR approved, QA approved, NLnet

#1104 bring changelog up to date
  CHANGELOG.md
Labels: documentation, needs CR

#1105 add a setting to workaround the GLES colorspace conversion issue
  interface/src/Menu.cpp
  interface/src/Menu.h
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/Basic2DWindowOpenGLDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.h
Labels: bug, CR approved, QA approved

#1094 Create App: Revolutionary "Paste" Url buttons for the "Create Model", "Create Material" and "Create Voxels" UI
  scripts/system/create/qml/NewMaterialDialog.qml
  scripts/system/create/qml/NewModelDialog.qml
  scripts/system/create/qml/NewPolyVoxDialog.qml
Labels: CR approved, QA approved

#1106 [ArmoredChat] Alleviate scrolling issue
  scripts/communityScripts/armored-chat/armored_chat.qml
Labels: CR approved, QA approved
