Repository overte-org/overte, pull requests merged in 2024-12, with the labels that each got.

#1211 Add .cache to gitignore for VSCode builds
  .gitignore
Labels: enhancement, CR approved, QA approved

#1274 Add a setting to hide the Graphics icon
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/ui/PreferencesDialog.cpp
Labels: enhancement, CR approved, QA approved

#1275 Graphics App: adding a setting to hide or display the app in the tablet/toolbar
  scripts/system/graphicsSettings.js
Labels: CR approved, QA approved

#1278 Add support for base64 images in image entity URLs
  libraries/entities/src/EntityItemPropertiesDocs.cpp
  libraries/material-networking/src/material-networking/TextureCache.cpp
  libraries/model-serializers/src/GLTFSerializer.cpp
Labels: enhancement, CR approved, needs QA

#1281 Update GitHub Actions
  .github/workflows/linux_server_build.yml
  .github/workflows/master_build.yml
  .github/workflows/master_deploy_apidocs.yml
  .github/workflows/master_deploy_doxygen.yml
  .github/workflows/pr_build.yml
  .github/workflows/release_build.yml
  tools/ci-scripts/linux-ci/Dockerfile_build_ubuntu-20.04
  tools/ci-scripts/linux-ci/Dockerfile_build_ubuntu-22.04
  tools/ci-scripts/rpm_package/Dockerfile_build_fedora-39
Labels: needs CR, server

#1214 update changelog for 2024.11.1
  CHANGELOG.md
Labels: documentation, CR approved
