Repository overte-org/overte, pull requests merged in 2025-06, with the labels that each got.

#1596 Fix "The compiler.cppstd is not defined for this configuration".
  tools/conan-profiles/vs-19-debug
  tools/conan-profiles/vs-19-debug-ninja
  tools/conan-profiles/vs-19-release
  tools/conan-profiles/vs-19-release-ninja
  tools/conan-profiles/vs-19-relwithdebinfo
  tools/conan-profiles/vs-22-debug
  tools/conan-profiles/vs-22-debug-ninja
  tools/conan-profiles/vs-22-release
  tools/conan-profiles/vs-22-release-ninja
  tools/conan-profiles/vs-22-relwithdebinfo
Labels: CR approved, Windows

#1590 Fix local entity grabbing on desktop
  scripts/simplifiedUI/ui/simplifiedNametag/resources/modules/nameTagListManager.js
  scripts/system/controllers/grab.js
Labels: CR approved, QA approved

#1531 material layering part 1: triplanar
  cmake/macros/AutoScribeShader.cmake
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/gpu/src/gpu/ShaderConstants.h
  libraries/graphics-scripting/src/graphics-scripting/Forward.h
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.cpp
  libraries/graphics/src/graphics/Material.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/graphics/src/graphics/Material.slh
  libraries/graphics/src/graphics/MaterialTextures.slh
  libraries/graphics/src/graphics/ShaderConstants.h
  libraries/procedural/src/procedural/ProceduralMaterialCache.cpp
  libraries/procedural/src/procedural/ProceduralMaterialCache.h
  libraries/procedural/src/procedural/ReferenceMaterial.cpp
  libraries/procedural/src/procedural/ReferenceMaterial.h
  libraries/render-utils/src/GlobalLight.slh
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/RenderPipelinesInit.cpp.in
  libraries/render-utils/src/model.slf
  libraries/render-utils/src/model.slv
  libraries/render-utils/src/render-utils/ShaderConstants.h
  libraries/render/src/render/ShapePipeline.cpp
  libraries/render/src/render/ShapePipeline.h
  libraries/shaders/src/shaders/Shaders.cpp
  libraries/shaders/src/shaders/Shaders.h
Labels: documentation, enhancement, question, work in progress, CR approved, QA approved, NLnet

#1242 fix noNetwork and add documentation for automated entity property files
  cmake/macros/GenerateEntityProperties.cmake
  libraries/entities/src/EntityItem.cpp.in
  libraries/entities/src/EntityItemGroupProperties.txt
  libraries/entities/src/EntityItemProperties.txt
Labels: documentation, CR approved, QA approved

#1584 CMake refactor
  .github/workflows/linux_server_build.yml
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
  .github/workflows/release_build.yml
  BUILD.md
  BUILD_LINUX.md
  BUILD_OSX.md
  CMakeLists.txt
  INSTALLER.md
  assignment-client/CMakeLists.txt
  cmake/compiler.cmake
  cmake/macros/AddCrashpad.cmake
  cmake/macros/AutoScribeShader.cmake
  cmake/macros/FixupInterface.cmake
  cmake/macros/FixupNitpick.cmake
  cmake/macros/GenerateInstallers.cmake
  cmake/macros/MemoryDebugger.cmake
  cmake/macros/OptionalWinExecutableSigning.cmake
  cmake/macros/SetPackagingParameters.cmake
  cmake/macros/SetupHifiClientServerPlugin.cmake
  cmake/macros/SetupHifiPlugin.cmake
  cmake/macros/TargetNsight.cmake
  cmake/templates/BuildInfo.h.in
  cmake/templates/console-build-info.json.in
  interface/CMakeLists.txt
  interface/src/Application_Setup.cpp
  interface/src/CrashRecoveryHandler.cpp
  launchers/qt/CMakeLists.txt
  libraries/auto-updater/src/AutoUpdater.cpp
  libraries/networking/src/crash-handler/CrashHandler.h
  libraries/networking/src/crash-handler/CrashHandlerBackend_Crashpad.cpp
  plugins/CMakeLists.txt
  plugins/oculus/CMakeLists.txt
  plugins/openvr/CMakeLists.txt
  plugins/opusCodec/CMakeLists.txt
  plugins/pcmCodec/CMakeLists.txt
  server-console/CMakeLists.txt
  tools/CMakeLists.txt
  tools/ci-scripts/upload.py
  tools/jsdoc/CMakeLists.txt
  tools/nitpick/CMakeLists.txt
Labels: CR approved, server, NLnet

#1413 add GPU driver blocklist
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Application_Events.cpp
Labels: enhancement, CR approved, Windows, needs QA, NLnet

#1632 Fix switching to desktop from OpenXR
  plugins/openxr/src/OpenXrContext.cpp
  plugins/openxr/src/OpenXrContext.h
  plugins/openxr/src/OpenXrDisplayPlugin.cpp
  plugins/openxr/src/OpenXrInputPlugin.cpp
Labels: CR approved, QA approved

#1595 Fix transparent SDF text antialiasing
  libraries/render-utils/src/sdf_text3D.slh
Labels: CR approved, QA approved

#1655 put back missing setUnscaledDimensions in setMaterialMappingMode
  libraries/entities/src/EntityItemProperties.txt
  libraries/entities/src/MaterialEntityItem.cpp.in
Labels: bug, CR approved, QA approved
