Repository overte-org/overte, pull requests merged in 2025-01, with the labels that each got.

#1288 Amended path to Rearranged_Basic_Sandbox.tar.gz
  server-console/src/main.js
Labels: bug, CR approved, QA approved

#1217 Camera clipping
  interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/CameraRootTransformNode.cpp
  interface/src/CameraRootTransformNode.h
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/scripting/RenderScriptingInterface.cpp
  interface/src/scripting/RenderScriptingInterface.h
  interface/src/ui/PreferencesDialog.cpp
  scripts/system/create/edit.js
Labels: needs CR, QA approved, NLnet

#1293 Implement network serializer (rebased)
  libraries/gpu/src/gpu/Texture.h
  libraries/gpu/src/gpu/Texture_ktx.cpp
  libraries/octree/src/OctreePacketData.cpp
  libraries/shared/src/AACube.h
  libraries/shared/src/BlendshapeConstants.h
  libraries/shared/src/SerDes.cpp
  libraries/shared/src/SerDes.h
  tests/ktx/src/KtxTests.cpp
  tests/ktx/src/KtxTests.h
  tests/shared/src/SerializerTests.cpp
  tests/shared/src/SerializerTests.h
Labels: CR approved, QA approved

#1276 Armored-Chat: Add sortOrder.
  scripts/communityScripts/armored-chat/armored_chat.js
Labels: CR approved

#938 Warnings as errors
  CMakeLists.txt
  assignment-client/src/AssignmentClientApp.cpp
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/audio/AudioMixerClientData.h
  assignment-client/src/audio/AudioMixerWorker.cpp
  assignment-client/src/audio/AudioMixerWorker.h
  cmake/compiler.cmake
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServerNodeData.cpp
  ice-server/src/IceServer.cpp
  interface/src/Application.cpp
  interface/src/AvatarBookmarks.cpp
  interface/src/avatar/AvatarPackager.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/raypick/PickScriptingInterface.cpp
  interface/src/raypick/RayPick.cpp
  interface/src/scripting/AssetMappingsScriptingInterface.cpp
  interface/src/scripting/TTSScriptingInterface.cpp
  interface/src/scripting/TTSScriptingInterface.h
  libraries/audio-client/src/AudioClient.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/entities/src/EntityItemProperties.cpp.in
  libraries/entities/src/ModelEntityItem.h.in
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/networking/src/Assignment.cpp
  libraries/networking/src/DataServerAccountInfo.cpp
  libraries/networking/src/HMACAuth.cpp
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/RSAKeypairGenerator.cpp
  libraries/networking/src/SockAddr.cpp
  libraries/networking/src/udt/Socket.cpp
  libraries/octree/src/OctreePacketData.cpp
  libraries/octree/src/OctreeQuery.cpp
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/procedural/src/procedural/Procedural.h
  libraries/recording/src/recording/Clip.cpp
  libraries/recording/src/recording/impl/PointerClip.cpp
  libraries/render-utils/src/RenderCommonTask.cpp
  libraries/render-utils/src/ToneMapAndResampleTask.cpp
  libraries/render-utils/src/text/Font.h
  libraries/render/src/render/ResampleTask.cpp
  libraries/shared/src/SharedUtil.cpp
  libraries/shared/src/WarningsSuppression.h
  libraries/shared/src/windowshacks.h
Labels: CR approved, Linux, Windows, QA approved, server, protocol change, NLnet
