Repository overte-org/overte, pull requests merged in 2025-04, with the labels that each got.

#1325 MVP OpenXR Support
  .github/workflows/pr_build.yml
  cmake/ports/hifi-client-deps/CONTROL
  cmake/ports/jsoncpp/portfile.cmake
  cmake/ports/jsoncpp/vcpkg.json
  cmake/ports/openxr-loader/fix-openxr-sdk-jsoncpp.patch
  cmake/ports/openxr-loader/portfile.cmake
  cmake/ports/openxr-loader/vcpkg.json
  interface/resources/controllers/openxr.json
  interface/src/Application.cpp
  interface/src/Application_Graphics.cpp
  interface/src/Application_Plugins.cpp
  interface/src/main.cpp
  libraries/controllers/src/controllers/UserInputMapper.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.h
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.cpp
  libraries/gpu/src/gpu/Backend.cpp
  libraries/shared/src/GLMHelpers.h
  libraries/shared/src/shared/Camera.h
  plugins/CMakeLists.txt
  plugins/openxr/CMakeLists.txt
  plugins/openxr/src/OpenXrContext.cpp
  plugins/openxr/src/OpenXrContext.h
  plugins/openxr/src/OpenXrDisplayPlugin.cpp
  plugins/openxr/src/OpenXrDisplayPlugin.h
  plugins/openxr/src/OpenXrInputPlugin.cpp
  plugins/openxr/src/OpenXrInputPlugin.h
  plugins/openxr/src/OpenXrProvider.cpp
  plugins/openxr/src/plugin.json
Labels: enhancement, CR approved, QA approved

#1317 Stop VR mouse capture.
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Application_UI.cpp
  interface/src/ui/PreferencesDialog.cpp
  libraries/display-plugins/src/display-plugins/CompositorHelper.cpp
  libraries/display-plugins/src/display-plugins/CompositorHelper.h
Labels: enhancement, CR approved, QA approved

#1321 fix domain entity lifetime in serverless mode
  libraries/entities/src/EntityTree.cpp
  libraries/physics/src/PhysicalEntitySimulation.cpp
Labels: bug, CR approved, QA approved

#1368 fix new warning
  interface/src/ui/Stats.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackendTransform.cpp
Labels: CR approved, QA approved, server, blocker

#1394 warning when avatar bookmarks JSON is malformed
  interface/src/Application.cpp
  interface/src/Bookmarks.cpp
  interface/src/Bookmarks.h
Labels: enhancement, CR approved, QA approved, NLnet

#1399 Fix keyboard preview not being unlit
  interface/src/ui/Keyboard.cpp
Labels: bug, CR approved, QA approved

#1382 Fix Armored Chat always scrolling on a new message
  scripts/communityScripts/armored-chat/armored_chat.qml
Labels: enhancement, CR approved, QA approved

#1367 Create App: Text Entity: Support for line breaks, Replace unlit material entity for shape unlit in selection tool
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
Labels: enhancement, CR approved, needs QA

#1407 fix font assert
  libraries/render-utils/src/text/Font.cpp
Labels: bug, CR approved, QA approved

#1335 Move to QCbor
  domain-server/src/DomainServerNodeData.cpp
  domain-server/src/DomainServerNodeData.h
  interface/src/AvatarBookmarks.cpp
  interface/src/avatar/AvatarPackager.cpp
  interface/src/avatar/MyAvatar.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/entities/src/EntityItemProperties.cpp.in
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/OctreeQuery.cpp
  libraries/recording/src/recording/Clip.cpp
  libraries/recording/src/recording/impl/PointerClip.cpp
Labels: CR approved, QA approved, server, protocol change

#1398 support PBR materials on polyvox, and triplanar material entities
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.h
  libraries/entities/src/EntityItemProperties.cpp.in
  libraries/entities/src/EntityItemPropertiesDocs.cpp
  libraries/entities/src/MaterialEntityItem.cpp.in
  libraries/graphics/src/graphics/Material.slh
  libraries/graphics/src/graphics/MaterialTextures.slh
  libraries/graphics/src/graphics/ShaderConstants.h
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/model.slf
  libraries/render-utils/src/model.slv
  libraries/render-utils/src/render-utils/model.slp
  libraries/render/src/render/ShapePipeline.h
  libraries/shared/src/MaterialMappingMode.cpp
  libraries/shared/src/MaterialMappingMode.h
  scripts/system/create/edit.js
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: documentation, enhancement, needs CR, needs QA, NLnet

#1393 ability to specify texture samplers
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackendPipeline.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLTexture.h
  libraries/gpu-gl/src/gpu/gl41/GL41Backend.h
  libraries/gpu-gl/src/gpu/gl41/GL41BackendTexture.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45Backend.h
  libraries/gpu-gl/src/gpu/gl45/GL45BackendTexture.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendVariableTexture.cpp
  libraries/gpu-gles/src/gpu/gles/GLESBackendTexture.cpp
  libraries/gpu/src/gpu/Batch.cpp
  libraries/gpu/src/gpu/Batch.h
  libraries/gpu/src/gpu/FrameIOKeys.h
  libraries/gpu/src/gpu/FrameReader.cpp
  libraries/gpu/src/gpu/FrameWriter.cpp
  libraries/gpu/src/gpu/Texture.cpp
  libraries/gpu/src/gpu/Texture.h
  libraries/graphics/src/graphics/Material.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/hfm/src/hfm/HFM.h
  libraries/model-serializers/src/GLTFSerializer.cpp
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/procedural/src/procedural/Procedural.h
  libraries/procedural/src/procedural/ProceduralMaterialCache.cpp
  libraries/procedural/src/procedural/ProceduralMaterialCache.h
  libraries/render-utils/src/RenderPipelines.cpp
Labels: documentation, enhancement, CR approved, QA approved, glTF, NLnet

#1354 add torus rendering
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
  libraries/entities/src/EntityItemProperties.txt
  libraries/entities/src/EntityItemPropertiesDocs.cpp
  libraries/entities/src/ShapeEntityItem.cpp.in
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/GeometryCache.h
  libraries/shared/src/EntityShape.cpp
  libraries/shared/src/EntityShape.h
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: documentation, enhancement, CR approved, needs QA, server, protocol change

#1412 VR Keyboard Shortcuts
  interface/resources/config/keyboard.json
  interface/resources/meshes/keyboard/key_copy.png
  interface/resources/meshes/keyboard/key_cut.png
  interface/resources/meshes/keyboard/key_down.png
  interface/resources/meshes/keyboard/key_left.png
  interface/resources/meshes/keyboard/key_paste.png
  interface/resources/meshes/keyboard/key_right.png
  interface/resources/meshes/keyboard/key_select_all.png
  interface/resources/meshes/keyboard/key_up.png
  interface/src/ui/Keyboard.cpp
  interface/src/ui/Keyboard.h
Labels: enhancement, CR approved, QA approved, NLnet, Controls / Interaction

#1423 Trigger click emulation for XR
  plugins/openxr/src/OpenXrInputPlugin.cpp
Labels: needs CR, needs QA, Controls / Interaction

#1416 automated render pipelines
  cmake/macros/AutoScribeShader.cmake
  cmake/macros/IncludeHifiLibraryHeaders.cmake
  cmake/macros/SetupHifiLibrary.cmake
  cmake/macros/SetupHifiProject.cmake
  interface/CMakeLists.txt
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/render-utils/CMakeLists.txt
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/RenderPipelines.h
  libraries/render-utils/src/RenderPipelinesInit.cpp.in
  libraries/render-utils/src/render-utils/model.slp
Labels: enhancement, CR approved, QA approved

#1437 OpenXR controller bindings for Odyssey+
  plugins/openxr/src/OpenXrContext.cpp
  plugins/openxr/src/OpenXrInputPlugin.cpp
Labels: bug, CR approved, QA approved, Controls / Interaction

#1417 support specifying per-texture texCoord set
  libraries/graphics/src/graphics/Material.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/graphics/src/graphics/Material.slh
  libraries/graphics/src/graphics/MaterialTextures.slh
  libraries/model-serializers/src/GLTFSerializer.cpp
  libraries/model-serializers/src/GLTFSerializer.h
  libraries/procedural/src/procedural/ProceduralCommon.slh
  libraries/procedural/src/procedural/ProceduralMaterialCache.cpp
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/render-utils/src/model.slf
  libraries/render-utils/src/model.slv
  libraries/render-utils/src/simple_procedural.slv
Labels: documentation, CR approved, QA approved, glTF

#1434 Bringing VRAM up to spec with latest cards.
  interface/src/Menu.cpp
  interface/src/Menu.h
Labels: CR approved, QA approved

#1440 Primary button for XR controllers without one
  plugins/openxr/src/OpenXrInputPlugin.cpp
Labels: bug, CR approved, QA approved, Controls / Interaction

#1445 add missing simple pipelines
  libraries/render-utils/src/GeometryCache.cpp
Labels: bug, CR approved, QA approved

#1447 another day another warning
  libraries/gpu/src/gpu/Buffer.h
Labels: CR approved, needs QA

#1467 Fix audio crashes in VR on Linux
  interface/src/Application_Setup.cpp
  interface/src/scripting/Audio.cpp
Labels: bug, CR approved, QA approved

#1469 Give JS console black default text color and disable rich text pasting
  interface/ui/console.ui
Labels: bug, CR approved, QA approved

#1460 Textareas for script fields in Create app
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: enhancement, CR approved, QA approved

#1471 Change "Interface already running" message to be a critical error…
  interface/src/main.cpp
Labels: CR approved

#1454 Replace Google WebRTC with PulseAudio's webrtc-audio-processing.
  cmake/macros/TargetWebRTC.cmake
  conanfile.py
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/shared/src/shared/WebRTC.h
  tools/conan-profiles/vs-19-debug
  tools/conan-profiles/vs-19-debug-ninja
  tools/conan-profiles/vs-19-release
  tools/conan-profiles/vs-19-release-ninja
  tools/conan-profiles/vs-19-relwithdebinfo
  tools/conan-profiles/vs-22-debug
  tools/conan-profiles/vs-22-debug-ninja
  tools/conan-profiles/vs-22-release
  tools/conan-profiles/vs-22-release-ninja
  tools/conan-profiles/vs-22-relwithdebinfo
Labels: CR approved

#1488 Stop testing your voice when closing the audio window
  interface/resources/qml/hifi/audio/LoopbackAudio.qml
Labels: enhancement, needs CR, needs QA

#1486 support normal mapping for triplanar materials
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/entities-renderer/src/paintStroke.slv
  libraries/entities-renderer/src/polyvox.slv
  libraries/entities-renderer/src/textured_particle.slv
  libraries/gpu/src/gpu/ShaderConstants.h
  libraries/gpu/src/gpu/Transform.slh
  libraries/graphics/src/graphics/MaterialTextures.slh
  libraries/graphics/src/graphics/ShaderConstants.h
  libraries/render-utils/src/grid.slv
  libraries/render-utils/src/model.slf
  libraries/render-utils/src/model.slv
  libraries/render-utils/src/render-utils/ShaderConstants.h
  libraries/render-utils/src/sdf_text3D.slv
  libraries/render-utils/src/simple.slv
  libraries/render-utils/src/simple_procedural.slv
  libraries/render-utils/src/standardTransformPNTC.slv
  libraries/render-utils/src/web_browser.slv
Labels: enhancement, needs CR, needs QA

#1494 Fix build error on newer compilers, add missing header
  libraries/recording/src/recording/Forward.h
Labels: CR approved

#1498 Change texture coordinate precision to 32 bit float
  libraries/model-baker/src/model-baker/BuildGraphicsMeshTask.cpp
Labels: bug, CR approved, QA approved

#1484 Prohibit characters option for TextField
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/controlsUit/TextField.qml
Labels: enhancement, CR approved, QA approved

#1392 fix material inspector not grabbing correct material sometimes
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: bug, CR approved, QA approved, NLnet

#1500 fix sampler assert
  libraries/gpu-gl-common/src/gpu/gl/GLBackendPipeline.cpp
  libraries/gpu/src/gpu/Batch.cpp
Labels: bug, CR approved, QA approved, blocker

#1503 Places App: Make navigation buttons not draggable
  scripts/system/places/places.html
Labels: CR approved, QA approved
