Repository overte-org/overte, pull requests merged in 2025-10, with the labels that each got.

#1831 Qt6: QML render target now set up properly, QML web entities rendering
  libraries/qml/src/qml/impl/RenderEventHandler.cpp
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/qml/src/qml/impl/SharedObject.h
Labels: CR approved, needs QA

#1461 normal map attenuation properties
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.h
  libraries/entities/src/EntityItemGroupProperties.txt
  libraries/entities/src/EntityItemProperties.cpp.in
  libraries/entities/src/EntityItemProperties.txt
  libraries/entities/src/EntityItemPropertiesDocs.cpp
  libraries/entities/src/EntityPropertyFlags.h.in
  libraries/entities/src/NormalMapAttenuationPropertyGroup.cpp.in
  libraries/entities/src/NormalMapAttenuationPropertyGroup.h.in
  libraries/entities/src/ZoneEntityItem.cpp.in
  libraries/entities/src/ZoneEntityItem.h.in
  libraries/graphics/src/graphics/MaterialTextures.slh
  libraries/graphics/src/graphics/NormalMapAttenuation.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/AssembleLightingStageTask.cpp
  libraries/render-utils/src/AssembleLightingStageTask.h
  libraries/render-utils/src/DeferredLightingEffect.cpp
  libraries/render-utils/src/DeferredLightingEffect.h
  libraries/render-utils/src/LightingModel.cpp
  libraries/render-utils/src/LightingModel.h
  libraries/render-utils/src/LightingModel.slh
  libraries/render-utils/src/NormalMapAttenuationStage.cpp
  libraries/render-utils/src/NormalMapAttenuationStage.h
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderForwardTask.cpp
  libraries/render-utils/src/UpdateSceneTask.cpp
  libraries/render-utils/src/ZoneRenderer.cpp
  libraries/render-utils/src/ZoneRenderer.h
  libraries/render-utils/src/model.slf
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/create/entityProperties/html/tabs/zone_normal_map_attenuation.png
Labels: CR approved, QA approved, protocol change, NLnet

#1828 Avoid division by 0 on web shader un-premultiply
  libraries/render-utils/src/web_browser.slf
Labels: bug, CR approved, QA approved
