Repository overte-org/overte, pull requests merged in 2025-09, with the labels that each got.

#1642 Enable default audio device in VR
  interface/src/scripting/AudioDevices.cpp
  libraries/audio-client/src/AudioClient.cpp
Labels: CR approved, QA approved, fix before release

#1790 Places App: Move the js out of the HTML
  scripts/system/places/places.html
  scripts/system/places/placesHtml.js
Labels: CR approved, QA approved

#1789 Document context menu action response JSON, cleaner prop names
  scripts/communityScripts/contextMenu.js
  scripts/modules/contextMenu.js
  scripts/tutorials/contextMenu/flashlight.js
  scripts/tutorials/contextMenu/localMirror.js
Labels: documentation, CR approved, fix before release

#1772 Replace QJsonDocument with nlohmann/json in shader cache
  libraries/gl/src/gl/GLShaders.cpp
Labels: CR approved, QA approved, fix before release

#1781 Fix multiple configuration errors
  interface/CMakeLists.txt
  libraries/image/src/image/TextureProcessing.cpp
  libraries/ui/CMakeLists.txt
  tools/nitpick/CMakeLists.txt
Labels: needs CR, needs QA, build system

#1797 Try to avoid hitting Windows' PATH limit when building Qt.
  .github/actions/setup-conan/action.yml
  .github/workflows/nightly_build.yml
  .github/workflows/pr_build.yml
  .github/workflows/release_build.yml
Labels: CR approved

#1571 Use window aspect ratio for VR preview rather than hardcoded 16:9
  libraries/display-plugins/src/display-plugins/hmd/HmdDisplayPlugin.cpp
Labels: CR approved, QA approved

#1812 Create App: Fix the Sound Entity overlay Icon that was render full black
  scripts/system/create/assets/images/icon-sound.svg
Labels: CR approved

#1809 Move GCC 15 workaround to the default Conan profile on Linux CI
  .github/actions/conan-install/action.yml
  .github/actions/setup-conan/action.yml
Labels: CR approved

#1819 Fix transparent web entity alpha
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/render-utils/src/web_browser.slf
Labels: bug, CR approved, QA approved
