Repository overte-org/overte, pull requests merged in 2025-02, with the labels that each got.

#1296 Places app: Portal Spawner and Copy URL
  libraries/entities/src/EntityTypes.h
  libraries/shared/src/PickFilter.h
  scripts/system/places/icons/portalFX.png
  scripts/system/places/places.css
  scripts/system/places/places.html
  scripts/system/places/places.js
  scripts/system/places/portal.js
  scripts/system/places/sounds/portalSound.mp3
  scripts/system/places/sounds/teleportSound.mp3
Labels: enhancement, CR approved, QA approved

#1302 Remove missed comment about removing dependency on script library.
  libraries/shared/CMakeLists.txt
Labels: CR approved

#1304 Places App: Addressing ugly image "broken link" in Place Details
  scripts/system/places/places.html
Labels: CR approved

#939 Refactor Application.cpp
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/ApplicationEventHandler.h
  interface/src/ApplicationMeshProvider.h
  interface/src/Application_Assets.cpp
  interface/src/Application_Camera.cpp
  interface/src/Application_Entities.cpp
  interface/src/Application_Events.cpp
  interface/src/Application_Graphics.cpp
  interface/src/Application_Plugins.cpp
  interface/src/Application_Setup.cpp
  interface/src/Application_UI.cpp
  interface/src/ArchiveDownloadInterface.cpp
  interface/src/ArchiveDownloadInterface.h
  interface/src/CrashRecoveryHandler.cpp
  interface/src/CrashRecoveryHandler.h
  interface/src/DeadlockWatchdog.cpp
  interface/src/DeadlockWatchdog.h
  interface/src/LODManager.cpp
  interface/src/WindowsSystemInfo.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyHead.cpp
  interface/src/graphics/RenderEventHandler.cpp
  interface/src/main.cpp
  interface/src/octree/OctreePacketProcessor.cpp
  interface/src/octree/OctreePacketProcessor.h
  interface/src/raypick/PointerScriptingInterface.cpp
  interface/src/scripting/Audio.h
  interface/src/scripting/AudioDevices.cpp
  interface/src/scripting/PerformanceScriptingInterface.cpp
  interface/src/scripting/RenderScriptingInterface.cpp
  interface/src/ui/HMDToolsDialog.cpp
  interface/src/ui/JSConsole.cpp
  interface/src/ui/OctreeStatsDialog.cpp
  interface/src/ui/OctreeStatsProvider.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/HifiAudioDeviceInfo.cpp
  libraries/audio-client/src/HifiAudioDeviceInfo.h
  libraries/networking/src/NodeList.cpp
  libraries/render-utils/src/AbstractViewStateInterface.h
Labels: CR approved, QA approved, NLnet
