Repository overte-org/overte, pull requests merged in 2025-07, with the labels that each got.

#1659 Armored Chat minor refactoring
  scripts/communityScripts/armored-chat/armored_chat.js
  scripts/communityScripts/armored-chat/armored_chat.qml
  scripts/communityScripts/armored-chat/qml/ChatMessage.qml
Labels: enhancement, CR approved, QA approved

#1664 Fix chat notification height on VR HUD
  scripts/communityScripts/notificationCore/notificationCore.js
Labels: bug, CR approved, QA approved

#1661 'OpenXR not supported on Wayland' message box
  plugins/openxr/src/OpenXrContext.cpp
  plugins/openxr/src/OpenXrContext.h
Labels: CR approved, Linux, QA approved

#1647 Fix laser grabs on local entities
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/controllers/controllerModules/farGrabEntity.js
  scripts/system/controllers/controllerModules/farTrigger.js
Labels: CR approved, QA approved, Controls / Interaction

#1670 Hotfix for chat
  scripts/communityScripts/armored-chat/armored_chat.qml
  scripts/communityScripts/armored-chat/qml/ChatMessage.qml
Labels: CR approved, QA approved

#1564 Thumbstick scrolling
  interface/resources/controllers/standard.json
  interface/src/raypick/PathPointer.cpp
  interface/src/raypick/PathPointer.h
  interface/src/raypick/StylusPointer.cpp
  interface/src/raypick/StylusPointer.h
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/Overlays.h
  libraries/controllers/src/controllers/ScriptingInterface.cpp
  libraries/controllers/src/controllers/ScriptingInterface.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/pointers/src/Pointer.cpp
  libraries/pointers/src/Pointer.h
  libraries/pointers/src/PointerManager.h
  libraries/script-engine/src/PointerEvent.cpp
  libraries/script-engine/src/PointerEvent.h
  libraries/ui/src/OffscreenUi.cpp
  libraries/ui/src/ui/OffscreenQmlSurface.cpp
  plugins/openxr/src/OpenXrInputPlugin.cpp
  plugins/openxr/src/OpenXrInputPlugin.h
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/hudOverlayPointer.js
  scripts/system/controllers/controllerModules/webSurfaceLaserInput.js
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: enhancement, CR approved, needs QA, Controls / Interaction

#1695 Only capture relevant thumbstick for scrolling, remove trigger requirement for Web entity scrolling
  interface/src/raypick/PathPointer.cpp
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/hudOverlayPointer.js
  scripts/system/controllers/controllerModules/webSurfaceLaserInput.js
Labels: CR approved, QA approved, Controls / Interaction

#1705 more warnings as errors
  interface/src/Application_Events.cpp
  libraries/graphics/src/graphics/Material.cpp
  libraries/platform/src/platform/backend/PlatformInstance.cpp
Labels: CR approved

#1704 splash screen shader compilation message
  interface/resources/images/splashShaders.png
  interface/resources/shaders/splashSkybox.frag
  interface/src/graphics/GraphicsEngine.cpp
  interface/src/graphics/GraphicsEngine.h
Labels: enhancement, CR approved, QA approved

#1686 Add LOD settings to Settings 'Graphics' page
  scripts/system/settings/qml/pages/GraphicsSettings.qml
Labels: enhancement, CR approved, QA approved, regression

#1696 Move CMake defaults to conanfile.py
  CMakeLists.txt
  conanfile.py
Labels: bug, CR approved, needs QA, build system
