Repository overte-org/overte, pull requests merged in 2025-08, with the labels that each got.

#1716 Fix a texture slot being overwritten by texture table on 2 layer and 3 layer materials.
  libraries/gpu/src/gpu/Batch.cpp
  libraries/gpu/src/gpu/FrameReader.cpp
  libraries/gpu/src/gpu/TextureTable.cpp
  libraries/gpu/src/gpu/TextureTable.h
  libraries/graphics/src/graphics/Material.cpp
  libraries/graphics/src/graphics/MaterialTextures.slh
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/render-utils/src/RenderPipelines.cpp
Labels: CR approved, QA approved

#1736 Fix About.buildDate
  interface/src/AboutUtil.cpp
  interface/src/AboutUtil.h
Labels: bug, CR approved, QA approved

#1644 Unmute microphone on first run
  interface/src/scripting/Audio.h
Labels: question, CR approved, QA approved

#1740 Default to high graphics setting on Linux on first start
  libraries/platform/src/platform/Profiler.cpp
  libraries/shared/src/GPUIdent.cpp
Labels: CR approved, QA approved

#1692 API to hide desktop menu bar while keeping menu items
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Application_UI.cpp
  interface/src/scripting/MenuScriptingInterface.cpp
  interface/src/scripting/MenuScriptingInterface.h
  scripts/system/menu.js
Labels: enhancement, needs CR, QA approved

#1745 Fix cache miss on Windows CI pipeline
  .github/actions/conan-install/action.yml
  .github/actions/setup-conan/action.yml
  conanfile.py
Labels: CR approved

#1748 Remove qtaudio_windows.dll QtMultimedia plugin
  cmake/macros/PackageLibrariesForDeployment.cmake
  cmake/templates/NSIS.template.in
  interface/src/Application_Setup.cpp
Labels: CR approved, Windows

#1765 fresh warning
  libraries/procedural/src/procedural/Procedural.cpp
Labels: CR approved

#1746 Fix stuff I broke with the VR lasers
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/controllers/controllerModules/farGrabEntity.js
  scripts/system/controllers/controllerModules/hudOverlayPointer.js
  scripts/system/controllers/controllerModules/webSurfaceLaserInput.js
Labels: bug, CR approved, QA approved, Controls / Interaction

#1768 ContextMenu disable/enable API, Snap app tweaks
  scripts/communityScripts/contextMenu.js
  scripts/modules/contextMenu.js
  scripts/system/html/SnapshotReview.html
  scripts/system/html/css/SnapshotReview.css
  scripts/system/html/js/SnapshotReview.js
  scripts/system/snapshot.js
Labels: CR approved, QA approved

#1769 Use Depot.dev for Windows CI builds
  .github/workflows/nightly_build.yml
  .github/workflows/pr_build.yml
  .github/workflows/release_build.yml
  README.md
Labels: CR approved

#1710 VR keyboard fixes, bugged scaling workaround
  interface/resources/config/keyboard.json
  interface/src/ui/Keyboard.cpp
Labels: bug, CR approved, QA approved, Controls / Interaction

#1723 Permission-protected LocationBookmarks API extension
  interface/resources/qml/hifi/dialogs/security/ScriptSecurity.qml
  interface/src/AvatarBookmarks.h
  interface/src/LocationBookmarks.cpp
  interface/src/LocationBookmarks.h
  libraries/script-engine/src/ScriptPermissions.cpp
  libraries/script-engine/src/ScriptPermissions.h
Labels: documentation, enhancement, CR approved, QA approved

#1583 OpenXR Body Tracking, Palm Pose
  interface/resources/controllers/openxr.json
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
  interface/resources/qml/hifi/tablet/OpenXrConfiguration.qml
  interface/src/main.cpp
  plugins/openxr/src/OpenXrContext.cpp
  plugins/openxr/src/OpenXrContext.h
  plugins/openxr/src/OpenXrInputPlugin.cpp
  plugins/openxr/src/OpenXrInputPlugin.h
  plugins/openxr/src/vendored_headers/XR_MNDX_xdev_space.h
  plugins/openxr/src/vendored_headers/openxr_extension_helpers.h
Labels: enhancement, CR approved, QA approved, Controls / Interaction

#1786 Swap out Reinhard and Filmic tonemaps for nicer looking variants
  libraries/render-utils/src/toneMapping.slf
Labels: enhancement, CR approved, QA approved
