Repository overte-org/overte, pull requests merged in 2025-05, with the labels that each got.

#1427 Conan: Initial AppImage packaging on Conan.
  .github/workflows/pr_build.yml
  INSTALLER.md
  cmake/macros/GenerateInstallers.cmake
  cmake/modules/GenerateAppImage.cmake
  interface/icon/interface.svg
  interface/org.overte.interface.appdata.xml
  interface/org.overte.interface.desktop
Labels: CR approved, QA approved, NLnet

#1504 Change default PolyLine texture to whitePixel.png
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
Labels: bug, CR approved, QA approved

#1505 OpenXR Hand Tracking
  interface/resources/controllers/openxr.json
  plugins/openxr/src/OpenXrContext.cpp
  plugins/openxr/src/OpenXrContext.h
  plugins/openxr/src/OpenXrInputPlugin.cpp
  plugins/openxr/src/OpenXrInputPlugin.h
  scripts/system/libraries/controllerDispatcherUtils.js
Labels: CR approved, QA approved, NLnet, Controls / Interaction

#1508 Squeeze force for grab on Index, tweak offsets for non-Vive controllers, xrNoHandTracking debug option
  interface/src/main.cpp
  plugins/openxr/src/OpenXrContext.cpp
  plugins/openxr/src/OpenXrContext.h
  plugins/openxr/src/OpenXrInputPlugin.cpp
Labels: CR approved, QA approved, Controls / Interaction

#1472 Dark theme setting
  interface/resources/styles/log_dialog.qss
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Application_UI.cpp
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/BaseLogDialog.cpp
  interface/src/ui/LogDialog.cpp
  interface/src/ui/PreferencesDialog.cpp
Labels: enhancement, CR approved, QA approved

#1451 Use GitHub hosted Runners.
  .github/workflows/linux_server_build.yml
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
  .github/workflows/release_build.yml
Labels: needs CR

#1476 Conan: Updates to GitHub Actions
  .github/actions/conan-install/action.yml
  .github/actions/setup-conan/action.yml
  .github/workflows/linux_server_build.yml
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
  .github/workflows/release_build.yml
  cmake/compiler.cmake
Labels: needs CR, server

#1516 OpenXR cleanup 2, electric boogaloo
  interface/resources/controllers/openxr.json
  interface/resources/controllers/standard.json
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.h
  libraries/shared/src/Transform.h
  plugins/openvr/src/OpenVrHelpers.cpp
  plugins/openxr/CMakeLists.txt
  plugins/openxr/src/OpenXrContext.cpp
  plugins/openxr/src/OpenXrDisplayPlugin.cpp
  plugins/openxr/src/OpenXrDisplayPlugin.h
  plugins/openxr/src/OpenXrInputPlugin.cpp
  plugins/openxr/src/OpenXrInputPlugin.h
  scripts/system/controllers/toggleAdvancedMovementForHandControllers.js
Labels: bug, CR approved, QA approved

#1513 Fix VR teleport indicator
  scripts/system/controllers/controllerModules/teleport.js
Labels: bug, CR approved, QA approved

#1523 Fix falling though the ground after serverless
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Application_Entities.cpp
Labels: bug, CR approved, QA approved

#1509 2025.05.1 changelog
  CHANGELOG.md
Labels: documentation, CR approved

#1551 De-downgrade SPRIV-cross, SPIRV-tools and glslang.
  conanfile.py
Labels: CR approved, QA approved

#1563 Fix blur taps alignment issue
  libraries/render/src/render/BlurTask.cpp
  libraries/render/src/render/BlurTask.h
  libraries/render/src/render/BlurTask.slh
Labels: bug, CR approved, QA approved

#1491 Fix "QML AnimatedImage: Error Reading Animated Image File" warning.
  scripts/system/assets/images/tools/progress-background.svg
  scripts/system/libraries/progressDialog.js
Labels: CR approved

#1543 GitHub Actions Runner image update
  .github/actions/setup-conan/action.yml
  .github/workflows/linux_server_build.yml
  .github/workflows/pr_build.yml
  tools/ci-scripts/deb_package/Dockerfile_build_debian-11
  tools/ci-scripts/deb_package/Dockerfile_build_debian-12
  tools/ci-scripts/deb_package/Dockerfile_build_debian-13
  tools/ci-scripts/deb_package/Dockerfile_build_ubuntu-20.04
  tools/ci-scripts/deb_package/Dockerfile_build_ubuntu-22.04
  tools/ci-scripts/deb_package/Dockerfile_build_ubuntu-24.04
  tools/ci-scripts/linux-ci/Dockerfile_build_ubuntu-20.04
  tools/ci-scripts/linux-ci/Dockerfile_build_ubuntu-22.04
  tools/ci-scripts/rpm_package/Dockerfile_build_fedora-40
  tools/ci-scripts/rpm_package/Dockerfile_build_fedora-41
  tools/ci-scripts/rpm_package/Dockerfile_build_fedora-42
  tools/ci-scripts/rpm_package/Dockerfile_build_rockylinux-9
Labels: CR approved, server

#1538 Dark theme for JS console
  interface/resources/styles/console.qss
  interface/src/ui/JSConsole.cpp
  interface/src/ui/JSConsole.h
  interface/ui/console.ui
Labels: CR approved, QA approved
