Repository overte-org/overte, pull requests merged in 2025-03, with the labels that each got.

#1331 Always show "Load Defaults" in "Running Scripts", not just when the developer menu is enabled.
  interface/resources/qml/hifi/dialogs/RunningScripts.qml
Labels: CR approved, QA approved

#1330 fix script initialization order bug
  interface/src/Application_Setup.cpp
Labels: bug, CR approved, QA approved

#1318 Fix VR Preview on Linux with Mesa drivers
  libraries/gl/src/gl/Config.cpp
Labels: CR approved, Linux

#1360 fix long startup times
  libraries/render-utils/src/RenderDeferredTask.cpp
Labels: bug, CR approved, QA approved

#1358 Initial fix for blurry/noisy transparencies on TAA
  libraries/render-utils/src/DeferredBufferWrite.slh
  libraries/render-utils/src/RenderDeferredTask.cpp
  libraries/render-utils/src/RenderDeferredTask.h
Labels: bug, CR approved, QA approved

#1365 2025.3.2 changelog
  CHANGELOG.md
Labels: documentation, CR approved

#1371 Rip out Highcharts proprietary graphing code.
  domain-server/resources/web/stats/index.shtml
  domain-server/resources/web/stats/js/highcharts-custom.js
  domain-server/resources/web/stats/js/stats.js
Labels: CR approved, QA approved
